### ISSUE TITLE
Request: Add "Usage" as a secondary sorting method for Powers.

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#103]
By default it is sorted by Usage first, with Action as secondary. I personally would love to have the option to make it the exact opposite. You already have Action as a valid first sorting method, but would it be possible to get usage as a secondary so we can set it to sort at-wills first, encounters second, etc, all within their own action groupings, and sort alphabetically as a tertiary?

**Comment by Marcloure** [comment]
So, we can group powers by action and sort them by usage, but the order would be **At-Will -> Daily -> Encounter**, since "daily" comes before "encounter", alphabetically speaking.

**Comment by NuptupTDOW** [comment]
Just bumping this from before since it's still something requested from my players. 

I'm not sure if there's a good way to make it work, maybe changing the tagging for how it searches for the handles to make it display correctly? But, overall, the most requested thing from all of my players has been one of these two options for sorting powers. 

Main Preference: GroupBy(Action) > SortBy(Usage) > Alphabetical beyond that. So, it would sort out as follows (and more importantly to them,) and would look as follows in Token Action HUD.

Standard Actions
     At Will (Eldritch Bolt), At Will (Flesh Rend), EtcEtc (following alphabetical at-wills), Encounter (Spirit Flay), Encounter (Treacherous Advantage), Encounter (Treacherous Advantage [Second Attack]), EtcEtc (alphabetical encounters), Daily (Your Glorious Sacrifice), EtcEtc (Following ABC's)

Move Actions
     (Same as Above)

Minor Actions
     (Same as Above)

Etc

If that's not possible because encounters have to sort after dailies, then my question becomes "Why does it work when Usage is the primary method, but wouldn't work with it as the secondary?" And, I think genuinely my players would still be fine with At-Will -> Daily -> Encounter. They mainly just don't like them all jumbled together since the only way to "hard sort" them is by numbering every single power and sorting by ItemName, but then your text output has numbers which, while effective, is a little jank. 

Which brings up the second idea which is, "Can we get a SortBy option that simply allows us to manually order them?" Whether this is achieved by creating a small text box on each power to input a 2 digit number that then is used for sorting, but not a part of the name, or by adding handles that we can grab and drag up or down to rearrange the list (something my players have very adamantly wanted for feats as well), or some other method. 

I think either option would be a great addition, with my personal preference being the ability to just manually set the sort order by typing a 2-digit number inside a small text box next to each power's name (and feats and all the other stuff :D). 

This might just be a pipe-dream, but I feel like, since manually numbering the names and using ItemName as the SortBy option works, there should be a way to make "NumericalOrder" work as the SortBy option, and just use a lot of the same code as ItemName, but direct it to look inside the new textbox instead of the power's name.

I hope to hear back about this. I genuinely think it'd be a great addition.

**Comment by EndlesNights** [comment]
Totally forgot about this, sorry. Added in the extra sort option, as well as havening a tertiary alphabetical sorting apply after the primary sorting.
I'll see about getting a no sort with drag and drop custom orders in as well in the near future.

**Comment by NuptupTDOW** [comment]
You are the hero we all needed! Not just you, everyone who works on this, but you certainly got this ball rolling. Thanks! I'll close this here since, it's coming along!
