### ISSUE TITLE
Weapon Required: Melee/ranged/implement with specific set to None should allow rolls without a weapon

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#110]
@draconas1 is looking at this

The 2 "weapon Required" boxes.  How I think they should interact is if I set the second box (Default/Default off-hand/None) to None that it would not enforce needing a weapon to roll the power?  The weapon rtequired is how the [weapon] or [implement] keywords are generated.  

Because that is not the case and you get the "you need a weapon equipped" for this power when you try to roll.  

From my (potentially wrong) understanding of the code I think the problem is Helper.getWeaponUse() is returning null both to indicate "not needed" and to indicate "I didn't find a weapon for use with this power" which is not being correctly trapped by the next check in rollAttack()

**Comment by EndlesNights** [comment]
Someone added this in a merge request, I wonder who that was?
