### ISSUE TITLE
Implement Power Damage Not Working

### ISSUE THREAD

**Issue by ghost** [EndlesNights/dnd4eBeta#116]
Having updated the 4e foundry suddenly characters are not working. Attack and damage rolls for weapon powers work just fine. Implement attack works. Damage creates an error. 

> Uncaught (in promise) TypeError: Cannot read properties of entity.js:927
> undefined(reading 'parts')
> [Detected 1 package; system:dnd4e]
> at Item4e.RollDamage (entity.js:927)
> at Function._onChatCardAction (entity.js:927)
> at HTMLElement.dispatch (jquery.min.js:2)
> at HTMLElement.v.handle (jquery.min.js:2)

**Comment by EndlesNights** [comment]
Would it be possible to see the damage formula that you're using please?

Or if you could please export the JSON for the power + weapon?
