### ISSUE TITLE
Critical damage broken with certain formulas.

### ISSUE THREAD

**Issue by absolitud3** [EndlesNights/dnd4eBeta#117]
Critical damage rolls currently don't work if you're using a weapon with special formulas for damage. As an example, one of my players has a 3d4 weapon and the Avenging Resolution feat (any damage die that results on a 1-2 is treated as a 3). The formula would be 3d4min3; The critical results in 3\*4min3, which Foundry can't read.

I've @'d Endles on Discord about this, but am creating the issue here so it's recorded properly.

**Comment by EndlesNights** [comment]
Under `Weapon Properties`, select the `Brutal` option, this will create a new field underneath of the `Weapon Damage Dice` labeled `Brutal Dice Value`. Enter a value of 3 there.

**Comment by absolitud3** [comment]
> Under `Weapon Properties`, select the `Brutal` option, this will create a new field underneath of the `Weapon Damage Dice` labeled `Brutal Dice Value`. Enter a value of 3 there.

Hi! Brutal is different from an effect such as Avenging Resolution, and they yield different averages. For example:
- A 2d6 with Brutal 2 can be represented by 2*(1d4+2), or 2d4+4, averaging 9.00.
- A 2d6 with "replace all results lower than 2 with 2" can be represented in Foundry with 2d6min2, averaging 7.33.

In the same way, 3d4 with Brutal 3 averages 12 (it's the only possible result, hehe), while 3d4min3 averages 9.75.

**Comment by EndlesNights** [comment]
My mistake, I can add a separate input field for additional roll options for non critical rolls.

**Comment by EndlesNights** [comment]
Should be good this time. I reworked Weapon Damage Dice to look like this: 
![image](https://user-images.githubusercontent.com/58280840/146312652-9b428fa9-7dfc-438c-b7f0-14b39b384959.png)
So you have the extra field to enter things into, and they won't be taken into account during crit roles

**Comment by absolitud3** [comment]
Awesome. Thanks a bunch!
