### ISSUE TITLE
Need D20 for damage rolls

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#118]
I came across the green slaad's "Chaos Bolt" power in the Monster Manual (p238), and it utilizes the d20 for damage.
![image](https://user-images.githubusercontent.com/5306827/145915131-42180708-e7dd-4de8-b984-9b4e42e646f7.png)

**Chaos Bolt (standard; at-will)**
Ranged 10; +21 vs. Will; 1d20 + 4 damage, and the target is dazed until the end of the slaad’s next turn.

No rush, but if d20 could be added to the Base Damage dropdown, then the green slaad would be happy.
![image](https://user-images.githubusercontent.com/5306827/145915335-ecb91fa7-a22c-4df2-a835-70e42cc41c54.png)

Cheers, and thanks again for rocking this DND4E module.

**Comment by EndlesNights** [comment]
Sure thing, I want to make the Green Slaad happy. Will be in the next patch.
