### ISSUE TITLE
[[@statMod]] is wrong if used more than once in a power's text fields

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#119]
I've noticed that I use the ` @statMod` syntax to refer to the same stat twice in a power's text fields, the second instance evaluates to 0 (in the chat power card) or `@statMod` (in the character sheet summary). This persists across different fields (like if I use it once in Effect and once in Special, the one in the second field is wrong.) If the second value is a different stat, it evaluates correctly.

It works fine if I use `@abilities.stat.mod` instead of `@statMod` for the second value, which has been my workaround for now. But I assume it would be more desirable for `@statMod `to work no matter how many times it is used.

![image](https://user-images.githubusercontent.com/10067730/146309392-dd2b1545-62a3-4973-b14a-310f5986f5d7.png)
![image](https://user-images.githubusercontent.com/10067730/146309407-a0bd631d-4dd3-4198-83d0-ab5990d28980.png)

**Comment by EndlesNights** [comment]
Well it might have something to do with only using `replace `instead of `replaceAll` I will fix this right now.
