### ISSUE TITLE
Tool Rolls are from 5th edition?

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#128]
I suspect the concept of rolling with tools is a 5th edition holdover?  Having checked all my books I can't find a tool in 4E that is not ("add +2 to a skill check in a certain circumstance")   (Tools in 5th ed = "make a check of 1d20 + proficiency bonus + relevant attribute bonus" where relevant attribute is dependent on what you are trying to do with the tool)  

Looking at the tool roll tab and reading the code they look much more like they are geared for 5th edition.  Also the code around them in the roll code doesn't work as the form does not contain attribute, its a factor on the tool itself.  

Proposal:
Tool as a concept stays, as it makes them sort nicely for easy finding, but the roll component of tools is removed.

@EndlesNights this is one I can pick up if you agree.

**Comment by ahoward-cf** [comment]
Counter-proposal:

Keep a "roll" button for tools, but have it apply the bonus. 

There will be situations in which skills are rolled without a tool to help them, and situations where tools will be used. Lazy players will generally prefer being asked to roll at "tool" check and clicking one button, to being asked to roll a "skill" check, and clicking 2 (one for the roll initiation, one for adding the bonus).

**Comment by draconas1** [comment]
Funnily enough @EndlesNights basically coded it to work like that, I was just getting confused when reading bits of the code.  

I have put a few clarifications in PR #146 which closes this.
