### ISSUE TITLE
"Weight" entry does not allow for text input

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#13]
I personally prefer descriptors for things like height and weight instead of just numerical values. Currently I can just put "Short" in the height box, but the weight box does not just allow "Lean" for example. I know you have plenty of arguably more important things than this to worry about, but when you get the time, it'd be a welcome change :D

**Comment by EndlesNights** [comment]
Weight as well as height will allow for text inputs now so you may use abstract words to describe values as apposed to exact numerical values.
