### ISSUE TITLE
Error after update to 0.2.51

### ISSUE THREAD

**Issue by Gallatus** [EndlesNights/dnd4eBeta#135]
Was working fine until the update for 0.2.51, then i keep getting this error after selecting "launch world": 

_"Error: The provided item type must be in the array of types defined by the game system."_

https://postimg.cc/McTcg6d2

**Comment by Gallatus** [comment]
This must be related to the update process. If i create a world from scratch, using 0.2.51 DnD4e, works fine. 
If i start the campaign stored before the update, it **crashes foundryvtt** (as in, i can't launch any world, 4e or 5e, nor update any modules).

**Comment by EndlesNights** [comment]
Could you please press F12 and open the console and see if you get an error message with more details? Based on what you described it might be that one of your items corrupted during the update?

**Comment by Gallatus** [comment]
You were right! Some of my content had !=admin rights. All fixed now.
