### ISSUE TITLE
Can't remove secondary Implement Critical Damage Formula box

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#138]
Click the minus, but it doesn't go away:

![image](https://user-images.githubusercontent.com/5306827/148488725-38777f99-85c2-49c0-9948-f53100d3ba2b.png)

Very low priority issue, but might be an easy fix or prevent some problems down the road...

**Comment by EndlesNights** [comment]
Thanks [draconas1](https://github.com/draconas1)
