### ISSUE TITLE
Can't drag power to macro bar

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#139]
Seems like whenever I try to drag a power from  a character sheet to a macro bar, I get a "game.macros.entities is undefined" JavaScript error instead. (Screenshot below from a test world with only libwrapper active)

![image](https://user-images.githubusercontent.com/10067730/148527936-aab2df4a-a776-4caf-ac51-b3462ce94bfb.png)

**Comment by EndlesNights** [comment]
Missed changing a deprecated call as part of converting from v8.x to v9. Will be fixed in the next patch.

Thanks for pointing it out.
