### ISSUE TITLE
Using a Situational Bonus and Combat Advantage does not calculate correctly

### ISSUE THREAD

**Issue by KinjeDL** [EndlesNights/dnd4eBeta#141]
It appears to be concatenating rather than adding (e.g. we added a +1 Situational bonus and Combat Advantage, and got +12 rather than +1 +2 it should have been.)

**Comment by EndlesNights** [comment]
Last patch should have resolved the issue.

**Comment by KinjeDL** [comment]
Confirmed, updated & tested working.

Thanks!
