### ISSUE TITLE
Player customisable @variables

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#142]
Thought / idea I am toying with on the general theme of making it easier to enter rolls and powers and figure out where bonuses come from.

While the effects system is nice it falls down a lot with conditional modifiers, which are most of 4E:
E.g. Weapon focus is +1 to damage when using a specific weapon category.  Expertise is similar.  There are feats for +2 damage to your arcane fire attacks. 

While you can enter them into the formula, you then have to remember where they came from - why is there an extra +1 on your `@wepAttack`?  At present my best answer is to use the [] notation to leave a note: `+1[WandExpFeat]`

Would be nice to be able to define some key-values somewhere e.g. `@AxeFocus = 2`, `@WandExpertise = 1` and then refer to them in formula.  Also makes it nicer when you get to Paragon and the bonuses get better.  

Triple bonus would be for a setting on those key value for "shows up in common modifiers" checkbox for combat powers.

My first thought for implementation was totally bespoke, which has the advantage of being in complete control of the UI and how it is shown to do some hand holding for less tech savvy players.  
But has the downside of having to build all that UI, and it not being very transferable - each player would need to implement them on their own characters with no way to share (without also implementing that in the style of the export/import json).

I then hit a second implementation idea, that I like better: to use the effect system. While you are supposed to refer to an attribute in the effect, there is nothing stopping you making the attribute `"WandExpertise"`  I define a standardised name for the overall effect "Conditional Bonuses" and simply looked for that effect when doing @variable replacements and add all kv attributes into the pool of potential data.  Again could define another effect "Situational Attack Bonuses" that would show up in the check list on the attack dialog.  

Reusing the effects dialog has the advantage of all the UI is already done, and because effects can be attached to items the DM can define some for common ones that the players can import.  It's not as intuitive, and I dislike systems that make use of special names to work, but it does get a lot of benefits in terms of time and effort and reuse.  

What are peoples thoughts on this as a worthwhile addition?

**Comment by ahoward-cf** [comment]
Honestly, I assumed something similar was always the end goal. Those
bonuses should be attached to feats which grant effects. Those effects are
auto-applied based on equipped weapon/power keywords.

Its a keyword system, and programming lends itself to keyword
implementation. Seems like an obvious (though probably difficult) solution.

Ultimately, I am guessing it will end up like the Starfinder system - all
the feats are items you drag in, which are tagged with effects, which get
auto-collected based on your action keywords. Making the keyword system
expansable will be the trick, which will enable homebrew. But thats for
later.

**Comment by draconas1** [comment]
>  Those bonuses should be attached to feats which grant effects. Those effects are auto-applied based on equipped weapon/power keywords. 

@ahoward-cf My knowledge on the active effects is still light, but I have not seen any way to filter an individual effect - it's either on and applying itself to a specific attribute, or its off.  So I can't see a way to auto apply based on keywords (though I would like to).  
Having effects making custom @variables that are available in code  is as good an implementation I can think of.

**Comment by ahoward-cf** [comment]
Powers already apply any bonuses from the weapons automatically. Part of
that check would also involve scanning the character for active effects,
checking their keywords, and applying the ones that match. I cant think of
a full code version but essentially you would activate a power. It would,
as part of its formula replacement, check for active effects with the same
key words as the power. It will also replace @wepAttack with the weapon
formula, which ALSO checks for active powers, this time that contain the
weapon keywords. We already sort of do this in several places
(replacing @wepAttack with the weapon formula, and cycling through the
ticked bonuses for the situational attack buffs).

I wont say its easy, but we have the bones already there.

**Comment by PaperMonkeyLord** [comment]
This is not worthless. In fact I agree with ahoward-cf. It feels like a natural progression.

**Comment by draconas1** [comment]
@ahoward-cf  so if I understand you right something like:
Effect : `weapon.axe.attack` or `power.damage.fire` and the attack / damage calculator would scan the keywords of the attack / damage and look for matching effects.  The before 2 triggering if it is a weapon attack and the weapon as the axe keyword and if the power damage type has the fire keyword.

**Comment by ahoward-cf** [comment]
That would be the general idea. I cant promise it wont involve a nightmare
of nested loops, but it should be fairly simple. In theory. Probably.

**Comment by draconas1** [comment]
#148 allows custom variables.  I have not looked at auto-applying effects yet as that's a bit more involved, but agree that in theory its not particularly complex.

**Comment by draconas1** [comment]
#149 goes the whole hog and allows for effects applying to attack and damage by keyword.

**Comment by draconas1** [comment]
I am declaring this done.
