### ISSUE TITLE
[Request] Temporary Effects That Don't Disappear Permanently

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#143]
When an effect is tied to wearable equipment, IE a piece of chest armor that when hit by fire attack, grants +1 item bonus to all defenses:

Currently, if you create a togglable effect that adds +1 to AC/Ref/Fort/Wil, you have to toggle it off manually at the end of the turn, as setting an effect to expire upon end of turn currently means it goes into a temporary effect state, and disappears from the armor completely when it meets its "end of 1 turn" condition. This works for consumables, but is not ideal for armor.

Disappearing effects is a great feature that has benefits, so I don't want to see it go away, but could there also be a temporary effect that instead of disappearing, automatically changes to passive state when it meets its end condition?

I apologize if this is redundant, but I don't see it in the list of issues.

**Comment by draconas1** [comment]
I can have a look when I poke custom effects, which I am inevitably going to, but where this may fall down is that we very much use the effect system as-is from foundry.  Their behaviour is what foundry has them do, so there will probably be a limit of what i can alter.

**Comment by drywallmud** [comment]
As passive and expired states are both possible I would say the issues I had here are addressed with effects in current state. 

I'm very grateful for the work put into the effects solutions. Closing this request.
