### ISSUE TITLE
Change attribute path to match foundry standard

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#16]
attribute.hp.value is the standard hp/health tracking that foundry uses, and 95% of modules utilize that specific stat by default. Would it be possible to change the stat you're using to match that standard so the system can have more module support without needing the module creator to make a system specific change or add something to there module that allows users to set what the module navigates to (which I can't seem to figure out.)

Example Modules are:
Combat Numbers
Monk's TokenBar
Token Health

**Comment by NuptupTDOW** [comment]
This kind of extends beyond just health, but health is the biggest, most common example. But, I know it would be a lot of work, but just having the system follow the standard foundry architecture would be amazing so more modules just work with no changes needed. Alternatively, know the shortcut to each desired attribute would be incredibly useful in making them work manually.

**Comment by 11-int** [comment]
If this change gets made the `resistences` attribute of actors is also spelled wrong

**Comment by EndlesNights** [comment]
Number of attributes have had their paths and spelling adjusted properly to match that of other systems.
