### ISSUE TITLE
Saving throw bonuses do not apply

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#167]
Choosing to add a passive +1 to saving throws (Human Perseverance Feat) can't be done.

I tried to create a feat with @data.details.saves.value with Add 1 in the feat maker, and it doesn't apply the bonus.

I also tried to create a +1 using the Saving Throw baked in bonus editor and I get this:

![image](https://user-images.githubusercontent.com/5306827/152918641-008baa86-246e-4b8b-8b3e-14248610b4ad.png)

We're currently just remembering to add the feat bonus, but so many saves and rolls happen that we have forgotten about the feat when the one character with the feat has a 9 roll save. Would love to see it fixed. 

(Also want to say that this is the best way to play 4E online. So grateful for this module.)

**Comment by draconas1** [comment]
@drywallmud I will get a fix written for that.
As a temporary measure you can turn off "show roll formula" in the system settings and it will work.

**Comment by draconas1** [comment]
@drywallmud 0.2.62 fixes this.
