### ISSUE TITLE
[Feature Request] Token Action HUD compatibility support.

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#17]
There is a module called Token Action HUD. Moving from D&D5e and from PF2e, all of my current D&D4e players miss this module a LOT. It is an excellent module that allows your entire character to be played without even needing the character sheet after initial set up. It's genuinely one of the best modules I've ever used and we all would love to see it supported for your system. I don't personally have the skills to make it happen, and the creator doesn't have the time to start a new system conversion. So, I turn to you, being a known capable foundry author and I wanted to ask if you would be willing to at least take a look at it and see if you could do it. They have instructions, but they require the converter to have knowledge of the system itself, which I lack. 

I'd greatly appreciate if you could at least take a look at it, and if you think you could do it, that'd be amazing!

**Comment by draconas1** [comment]
This is now done, Token Action Hud supports 4e

**Comment by EndlesNights** [comment]
Thank again draconas1!
