### ISSUE TITLE
No place to add Action Point riders

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#176]
Since just about every paragon path gets a bonus effect when using an action point, it would be really handy to have a place to enter such effects so they could also be added to the chat output. I know I tend to forget them a lot otherwise...

**Comment by draconas1** [comment]
Have submitted a PR for this,  you are not wrong, as my party have already forgotten their warlord bonuses to AP and its only been 2 sessions with a warlord!  

Half of this was already to go before I arrived - the sheet was setup to handle an "extra" field, so all I had to do was give you a way to populate it.

**Comment by FoxLee** [comment]
Added in the commit above.
