### ISSUE TITLE
Issues with Apply Damage and Resistances 

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#184]
Lumi has found issues with calculations when there is a multiplier:

Lumi, Unholy Ostler: @Draconas @EndlesNights I ran into some really funky behavior with Apply Damage right-click when the /roll includes * to multiply things.
For example /r 10*6 shows 60 as the roll result, but Apply Damage damage subtracts 16. It seems like it's calculating the * as a plus.
[04:06] Lumi, Unholy Ostler: /r 2*2*2 is -6, yep.
[04:09] Lumi, Unholy Ostler: Same with minus. :thunken:
[04:09] Lumi, Unholy Ostler: So somewhere the Apply Damage isn't using Roll.result correctly or something. 
[04:16] Lumi, Unholy Ostler: looks like applychatcarddamage is to blame
[04:18] Lumi, Unholy Ostler: 1d1+100-100 results in 201

Drac has also found issues with damage types:
When your damage roll involves 2 separate damage types, and the target is resistant to one of them, (e.g. 10 physical damage +5 fire damage (put in a secondary damage expression), target has resistance 5 fire) they are treated as having 0 resistance.  

When a damage has multiple types: e.g. 15 fire and lightning damage.  - the internal logging of damage types and amounts seems to split the damage up randomly.  I am not sure what's going on there and have not investigated it.  

Other things to investigate having gone to look at RAW in the rules compendium (p 224):
Half damage is applied at the end, so should be using the full amount for resistance calculations 
How resistance and vulnerability are applied to each other
How vulnerabilities apply the opposite way round to resistances for combine damage.

**Comment by Draconas** [comment]
*is randomly emailed this* hello o/

**Comment by draconas1** [comment]
New changes have broken the calculation in the other direction now:
Combined damage rolls work fine in all of the scenarios I outlined, but resistances now do not apply correctly for secondary damage.  
In effect, all damage is treated as having combined damage types.

Example:  Power that deals 10 (acid, thunder) + 5 (fire) secondary damage.
Target: Has resistance 10 acid, 5 thunder.  
Expected:  Target takes 5 (acid, thunder) damage and 5 fire damage.
Actual Result: Target takes 15 damage as its lowest resistance is fire at 0.  

I think fixing this requires altering the applyChatCardDamageInner method to correctly assign combined damage types.

**Comment by draconas1** [comment]
Have tried testing the various functions and think this is fixed in latest version.  Thanks @EndlesNights
