### ISSUE TITLE
Wearing armor without proficiency does not apply penalties to attacks and Reflex

### ISSUE THREAD

**Issue by jjhritz** [EndlesNights/dnd4eBeta#187]
From pg. 265 of the Rules Compendium:
> If an adventurer wears armor that he or she does not have proficiency with, the armor makes the adventurer clumsy and uncoordinated: That character takes a -2 penalty to attack rolls and to Reflex.

Nothing major, and something that rarely comes up in play, but I do actually have a Psion wearing scale armor as part of a disguise in the game I'm running.

**Comment by EndlesNights** [comment]
Should be addressing latest patch 0.2.66
