### ISSUE TITLE
Manual improvements

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#188]
Watching conversations and questions on discord:

Clarifications on how effects work and don't work - aka How manually implemented weapon/power effects are different from regular effects

What values you should poke for the major things you may want to edit with effects (with link to examples):
Defences
Skills
Surges
Speed
initaative

**Comment by Gallatus** [comment]
Still can't figure it out. Would love to use effects for each example above.

**Comment by draconas1** [comment]
@Gallatus the latest version has some improved documentation around effects and what attributes to poke.
