### ISSUE TITLE
@atkMod is suddenly a negative value when updating to newest release 3/1/22

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#189]
So, last night my character was getting their full attack bonus with their power. But today, for some reason, the character has a "-2" that is being calculated inside the @atkMod value of the formula. I have checked the power carefully and the weapon being used, but I can't find anything that would be causing this phantom -2 to appear. I briefly applied the marked status to the character and I took it off when I noticed the -2, but it didn't fix the problem so I am at a loss.

Any ideas why this would be happening?

**Comment by EndlesNights** [comment]
Yes, was a simple mistake I made, should be fixed with hotfix I did yesterday, have you tried patch 0.2.67?

**Comment by draconas1** [comment]
This took me a while to figure out on my characters.  (I have it on the latest version)

This is probably caused by them not being proficient in either their armour or shield.  If you edit their armour & shield and set to proficient the -2 should go away.

**Comment by NuptupTDOW** [comment]
Hmmm, so it was. Thanks! Let's call this resolved and close it. I'm just wondering why it suddenly wasn't proficient anymore. Armor was one of the first things I had added.
