### ISSUE TITLE
[Request] Power card default information for implements

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#192]
When changing a power to use an implement instead of a weapon, could it automatically change the power's attack formula, damage formula, and critical formula to replace the @wepAttack, @wepDamage and @wepCritBonus with their implement counterparts?

Ideally, this would be great if it could selectively change only those parts of the field instead of resetting the entire field, that way if someone put in their complex attack formula but forgot to change it to implement first, they won't lose all that work. 

If that's not possible, maybe have it check to see if the field has changed at all, and if it has (because user made their own formula), it won't change anything, but if it hasn't, it would just automatically replace the base formula with the correct one.

**Comment by draconas1** [comment]
If you have selected that the power is an implement power in the weapon required field, @wepX variables automatically flip to the implement values.

**Comment by NuptupTDOW** [comment]
huh........ well now i just feel dumb lol. Ok, thanks, i'll stop manually changing them then!
