### ISSUE TITLE
[Request] Formula Dropdown for NPC Power Cards

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#196]
Would it be possible to pull the attack formula string text value for the power card display for NPC sheets?

Right now, there is a blank option in the dropdown list, which will display "Attack" on the card (ie Attack vs AC). For monsters, the formula is usually two or three characters, something like "+5" "or "+12" which would be handier to see in the display than "Attack" when the DM is choosing what action to use.

Not a high priority feature, but one that I see value in, and would make the monster cards a little more sleek. Thanks for considering this request, and thanks for all the efforts on DND4E.

**Comment by drywallmud** [comment]
That's EXACTLY what I mean! 

Wow! Was this something in the works, or are you that fast? THANK YOU!

Is there a way to make it batch change the blank to "Attack Formula" for NPC powers when this rolls out?

**Comment by EndlesNights** [comment]
It was something I was thinking about the other day, and it was super simple to implement.

**Comment by draconas1** [comment]
Next build of creature exporter will set all powers to use this.
