### ISSUE TITLE
Dagger doesn't qualify as a ranged weapon for ranged weapon powers (like Basic Attack)

### ISSUE THREAD

**Issue by jjhritz** [EndlesNights/dnd4eBeta#197]
Rogue in my game tried to use Ranged Basic Attack with a dagger and couldn't make the attack because the ruleset didn't think he had a ranged weapon equipped.   Ranged attacks should also accept attacks with thrown melee weapons.

**Comment by EndlesNights** [comment]
Should be fixed with v0.2.71

**Comment by jjhritz** [comment]
Awesome, thank you!

We briefly worked around it by just setting the attack to use any weapon and specified the dagger in the "Weapon Required" section, but definitely will be nice to not have to worry about it in the future.
