### ISSUE TITLE
[Request] Quantities on Tabs on Character Sheets

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#199]
![image](https://user-images.githubusercontent.com/5306827/159093607-273e1f1e-1dda-4067-bf78-6c41262e010d.png)

I'm curious how difficult it would be to get a count right beside the text tabs. Very low priority UI feature, but something a DM suggested that would be helpful. It would also resolve the issue that I've been putting feats on monsters into the "Other" section of the powers list because multi-tasking DMs tend to overlook the feats tab on monsters and forget to add the +2 from an adjacent ally, etc, when its hiding on another tab that often goes empty. Just seeing a (1) on the feats would invite DM to peek.

It would also be helpful on inventory, as well as during data entry when building PCs. 

If its a big pain to implement, I totally understand, but since it would add value, it can't happen without being brought forward if someone is curious to try and tackle the request.

Thanks again for the efforts on this miracle of a 4e module.

**Comment by EndlesNights** [comment]
That seems like it could be possible. I know one of the things I wanted to test out but have yet to get around to it was combining the Powers and Feats tabs together for the NPC/Monster Sheet.

**Comment by drywallmud** [comment]
That would also be extremely helpful. This module is already packed with great features, and I'm confident the sheets and everything else will evolve in an amazing way.

**Comment by drywallmud** [comment]
As the workflow of the sheets have changed so much since the request was made, this has become such an unneeded option. I'm going to close this.
