### ISSUE TITLE
Actualization of Actor's Sheet after modification

### ISSUE THREAD

**Issue by 3E2NTI** [EndlesNights/dnd4eBeta#2]
After adding an item or a power in the actor sheet, it is often necessary to close and reload the sheet for the changes to take effect.

**Comment by NuptupTDOW** [comment]
I have this issue as well, and similar things when applying bonuses to NAD's, when you click the "Save" button, the dialog does not close and return you to the sheet.

**Comment by EndlesNights** [comment]
Do you think you could provide me with additional details of your setups, and an explicit step by step of the processes that's leading to the issue so that I may try to duplicate the results?

**Comment by NuptupTDOW** [comment]
So, After the charisma fix, I can't replicate the issue. It may have been some residual bugginess from that code error.

**Comment by NuptupTDOW** [comment]
I am not the original poster, but I believe this issue can be closed as I can no longer replicate it.

**Comment by 3E2NTI** [comment]
I can’t replicate the error either. It’s fixed :)
