### ISSUE TITLE
Null Values instead of 0 on crits.

### ISSUE THREAD

**Issue by mageofthesands** [EndlesNights/dnd4eBeta#20]
Foundry version 0.7.9
4th Edition Beta 0.0.9

When deleting the Enhancement values for a weapon, but not entering a new value, a zero is left behind.  Or appears to.  A critical hit returns null values.  Things return to normal by typing a zero for Enhancement value.
Suggestion: default to an actual zero when value is deleted, or leave the space blank so user knows a value is missing.
![cats](https://user-images.githubusercontent.com/81931767/116026062-87ef5600-a617-11eb-9a8f-600511c02705.jpg)

**Comment by EndlesNights** [comment]
Values should now properly default to zero instead of null or undefined in version 0.2.2
