### ISSUE TITLE
[Request?] Power "Tooltips" support? 

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#201]
So, this might just be a "way too big" kind of request, but I'd at least wanna get it mentioned in-case its not actually too difficult to pull off. 

So, I am looking for something like an MMO tooltip that appears either next to cursor, or in a user-designated position when the user mouse-over's a power or item that has been placed on the macro bar at the bottom of the screen (or more specifically inside of Token Action HUD, since I think if it works for one, it'll work for both?).

Essentially, I would just want it so that, if I as a GM/DM/Player select a token for a creature I control (NPC/Enemy/PC) and then move my cursor to the Token Action HUD and on top of a power or item or feat, it would be amazing if it would take what appears when you click the name of the power/item/feat in the character sheet (the dropdown preview), and then project that, exactly as it is, somewhere on the screen. 

For example: I have a Hexblade that uses Flesh Rend. It is an At-Will power. I think it would be really cool if I clicked my token, moused over TAH, then over my Flesh Rend power button, and somewhere on the screen, it would show me the exact text for the power I am hovering over, as if I had opened the character sheet, and then clicked the power's name to see it there. Same with Items and Feats. 

Again, I'm unsure how big of an undertaking this would be, but I think for 4th edition, the one that feels the most like a video game, it would be an excellent addition to the system to make it have that nice quality of life. 

Hope the idea isn't too wild, can't wait to hear back on it. Have a great time!

**Comment by EndlesNights** [comment]
Just a concept image, but something like this?

![image](https://user-images.githubusercontent.com/58280840/160193488-7e70b239-6e78-4cc5-a3be-0606fe76b642.png)

**Comment by NuptupTDOW** [comment]
Holy crap! Yes, that's pretty much EXACTLY what I'm looking for! Hopefully it'd work with macro bar as well, but definitely I feel like with how good TAH is, it's almost more important to get that functionality first? But yeah, that's exactly what I meant! All it would need now is the option to set where on the screen you want the tooltip to appear, whether "under power" or "drag to desired spot" or "pick a corner" for example. I would say that, any of the options that don't leave the box right next to the power you're hovering over would need to add the power name and color to the top. But, that's wayyyyyy extra. Just giving it the functionality you're showing in that screenshot already is soooo good man!

**Comment by NuptupTDOW** [comment]
Oh, just realized, for ranged and area powers, like the one you're demonstration uses, it would be great if it also showed that range or area on the tooltip. Or perhaps just created a highlight around the selected token on the map that shows "valid targetable squares".

**Comment by draconas1** [comment]
So I am afraid this is basically a no go with Token Action HUD. 

I don't think it has the ability to display those sorts of tooltips (or put it this way, it is not an advertised feature, and when I wrote the 4E integration it was not coded into the 5E integration which is the most feature-rich)

**Comment by NuptupTDOW** [comment]
Would it be possible to just code it to work with the macro bar at the bottom of the screen? Because, as far as I was aware, if you can make it work with the macro bar to pop up something anytime you hover over an action, then the system should just recognize that the token action HUD buttons are mechanically the same as mousing over a macro bar button. Isn't that how that works? Or am I completely misunderstanding how these things work? I had been under the assumption that token action hud pretty much worked as a super advanced macro bar at the bottom of the screen. So, anything that works with the macro bar would then work with token action hud.

**Comment by draconas1** [comment]
I'm not sure how possible it is an how much control we have over tooltips and how much information can go into them (e.g. possibly plain text only).  And the macros are more generic, not being simple skill links.  

Looking at the release notes for V10 (https://foundryvtt.com/releases/10.260 ) this may be something that has to wait until then when we get the unified tooltip api.  

Happy to be wrong, and if you have an example in another system / setting of someone doing advanced macro tooltips then we can have a look at it and see how they are doing it.

**Comment by NuptupTDOW** [comment]
I sadly do not, but I'll ask around and see if anyone knows of one. I feel like there's maybe some code that MIGHT be applicable in the playing card code, since you can kind of "hold them" and preview them. But, I've no clue. 

I'm glad to hear you at least might have an angle of attack to take with the future foundry release, so I'll just continue to support and wait patiently!

**Comment by NuptupTDOW** [comment]
> Looking at the release notes for V10 (https://foundryvtt.com/releases/10.260 ) this may be something that has to wait until then when we get the unified tooltip api.

So, with V10 out, does this possibility seem more plausible to see in the future? Not trying to rush or anything, just checking back in on a topic that's sat idle for a while.

**Comment by NuptupTDOW** [comment]
@draconas1 bump

**Comment by draconas1** [comment]
You are asking the wrong person, in order for us to have tooltips in TAH, first TAH has to support tooltips on mouse over the buttons.  Once that is a TAH feature I can look at integrating it with 4e.  

Putting displayable tooltips on generic buttons on the macro bar is also not my wheelhouse, basically anything involving UI's is not something I am good at or enjoy.  See that every UI commit of mine has a subsequent commit from EndlessNights, which they very politely do not call "making Drac's UI look less like ass", but that's what it is.  
Tooltips on the macro bar / random buttons does sound like something that someone would write a generic foundry module for in v10 - but may take a while for v10 to settle, so worth searching for those - again if someone has done the UI & hook work such that all I have is to call a hook and supply it with the right data, that is an easy job for me and one that I am likely to do.

**Comment by NuptupTDOW** [comment]
Gotcha, sorry... I guess I just didn't actually know WHO the right person was, since I'm not really super knowledgeable, so I just followed up with the last known point of contact. Sorry for rocking the boat as it were.

**Comment by draconas1** [comment]
No worries, and sorry for being a bit snippy.  Like I said, if you can convince someone / module / Token Action Hud to do do the tooltips I can happily do the 4E compatibility work on this side.

**Comment by draconas1** [comment]
This is now baked in to the 4e Token Action Core integration (https://github.com/draconas1/foundry-4e-tools) from version 3.2.0 for all items.   We are considering what to do about conditions
