### ISSUE TITLE
"Extra modifiers" field of weapon is appended to dice size in damage roll

### ISSUE THREAD

**Issue by jjhritz** [EndlesNights/dnd4eBeta#205]
Created an improvised weapon (2-handed, which means 1d8 damage) and adjusted the stats to reflect the "improvised missile" feat (+2 to attacks and damage with thrown improvised weapons).  When the character rolled damage with the Basic Attack (Ranged) power, the damage rolled was _1d82_, not 1d8 + 2.
![image](https://user-images.githubusercontent.com/17412506/162558330-72e381e8-2e30-4779-9984-a5db464d2166.png)
![image](https://user-images.githubusercontent.com/17412506/162557318-4c1ec485-ce51-4ae7-80f0-22144cf251ce.png)

Weapon JSON:
`{"_id":"esFemsXCOYd1KPzk","name":"Chair (Improvised)","type":"weapon","img":"icons/svg/item-bag.svg","data":{"description":{"value":"","chat":"","unidentified":""},"source":"","quantity":1,"weight":0,"price":"0","attuned":false,"equipped":true,"rarity":"","identified":true,"activation":{"type":"","cost":0,"condition":""},"duration":{"value":null,"units":""},"target":{"value":null,"width":null,"units":"","type":""},"range":{"value":5,"long":10,"units":""},"uses":{"value":0,"max":"0","per":""},"consume":{"type":"","target":"","amount":null},"armour":{"value":10},"hp":{"value":0,"max":0,"dt":null,"conditions":""},"macro":{"type":"script","scope":"global","launchOrder":"off","command":"","author":""},"level":null,"weaponType":"simpleM","weaponHand":"hMain","properties":{"amm":false,"bru":false,"def":false,"hic":false,"imp":false,"lof":false,"lom":false,"off":false,"rch":false,"rel":false,"sml":false,"spc":false,"thv":true,"tlg":false,"two":false,"ver":false},"proficient":true,"proficientI":false,"profBonus":2,"profImpBonus":0,"enhance":0,"isRanged":true,"damageDice":{"parts":[["1","8","2"]]},"damage":{"parts":[]},"damageCrit":{"parts":[]},"damageImp":{"parts":[]},"damageCritImp":{"parts":[]},"damageType":{"physical":true,"damage":false,"acid":false,"cold":false,"fire":false,"force":false,"lightning":false,"necrotic":false,"poison":false,"psychic":false,"radiant":false,"thunder":false},"brutalNum":1,"weaponGroup":{"axe":false,"blowgun":false,"bow":false,"cbow":false,"dragon":false,"flail":false,"garrote":false,"ham":false,"bladeH":false,"bladeL":false,"mace":false,"pik":false,"pole":false,"sling":false,"spear":false,"staff":false,"unarm":false,"whip":false},"attackForm":"@profBonus+@enhance","attackFormImp":"@profImpBonus+@enhanceImp","damageForm":"@enhance","damageFormImp":"@enhanceImp","critDamageForm":"(@enhance)d6","critDamageFormImp":"(@enhanceImp)d6","critRange":20,"critRangeImp":20,"chatFlavor":""},"effects":[],"folder":null,"sort":0,"permission":{"default":0,"Iq7MER5Zznr306Dt":3},"flags":{}}`

**Comment by EndlesNights** [comment]
This field is working as intended, as the Extra Modifiers are in reference to the Foundry Dice Modifiers found here: https://foundryvtt.com/article/dice-modifiers/

If you want to use if for damage modifiers you can, it's not the primary intent of the field though. And you would need to enter in a value of "+2" to get the desired effect. I would instead recommend that you use the Bonus to Primary Damage Formula instead.
