### ISSUE TITLE
[Bug] Replace all null roll variables with 0

### ISSUE THREAD

**Issue by BadgerKing7** [EndlesNights/dnd4eBeta#206]
Some variables are not replaced with `0` in the roll evaluation but with an empty string, such as `@wepAttack`, `@wepDamage` and `@wepCritBonus` at lines 522-524 in `module/helper.js`. This breaks some of the formula evaluation code in core Foundry.

As an example, `((0+1)d6 + 3 + 0)[radiant]` evaluates successfully, but evaluating `((0+1)d6 + 3 + )[radiant]` throws an uncaught error in Foundry 9.266.

This can be avoided if all variables are replaced with `0` instead of some begin replaced with empty strings.

**Comment by BadgerKing7** [comment]
The core-side issue can be tracked [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/6938).

**Comment by EndlesNights** [comment]
Should have gotten around to this way sooner, but thanks for writing the merge request. Will be part of patch 0.2.79.
