### ISSUE TITLE
Half Damage + resistances

### ISSUE THREAD

**Issue by Sherydanse** [EndlesNights/dnd4eBeta#211]
Hello. I have found a bug. Apply Half Damage button doesn't work correctly with resistances. Instead of Halfing the damage and then subtract resistance it first subtracts and the halfs the damage making resistances much less effective. Could you please investigate this issue

**Comment by EndlesNights** [comment]
That is working according to the rules:

> When a power or other effect deals half damage, first apply all modifiers to the damage, including resistances and vulnerabilities, and then divide the damage in half (rounded down).
> Example: Albanon the wizard is weakened and uses ice storm, which deals 16 cold damage to a fire giant that has vulnerable 5 cold. First add 5 to the 16 cold damage for the vulnerability, giving a result of 21. Then divide that result in half for the weakened condition. The giant ends up taking 10 cold damage.

Do you know of some other version of the rules that contradicts this?

**Comment by Sherydanse** [comment]
My mistake, over the years, I forgot that "half damage" has its own rules.

Thank you so much for your overall work. The cumbersomeness of non-automated mathematics in 4e puts a lot of people off compared to 5e, and your work allows you to attract people to this system.
