### ISSUE TITLE
Request:  Simplified NPC sheet

### ISSUE THREAD

**Issue by zk-sn** [EndlesNights/dnd4eBeta#22]
It would be nice if there was a sheet for NPCs in the style of monster / npc statblocks.  Trying to enter enemies onto PC sheets would quickly become problematic.  I was going to take a stab at making one but I am entirely lacking in HTML and CSS skills.

**Comment by drywallmud** [comment]
I'd like to submit this, on the off chance that this starting point saves anyone some time. If not, no worries. 

[Monster Card HTML.txt](https://github.com/EndlesNights/dnd4eBeta/files/6600812/Monster.Card.HTML.txt)

Cheers!

**Comment by EndlesNights** [comment]
Well the NPC sheet is not perfect but one currently exists. Work shall continue on it, but I will close this issue for the time being.
