### ISSUE TITLE
[Request] Option to make visible auras hidden with token visibility

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#222]
Is it possible to have a toggle checkbox such as "Aura only visible when token visible" and have the visible aura hidden while the creatures are hidden?

Not a high priority feature, but one I would certainly get lots of use out of.

Thanks again, getting so much out of this system!

**Comment by draconas1** [comment]
Not in the 4E system as auras are done by a separate module

**Comment by drywallmud** [comment]
My bad!
