### ISSUE TITLE
Any *.dnd4e import support?

### ISSUE THREAD

**Issue by dimitrievgs** [EndlesNights/dnd4eBeta#227]
As I see there is an json export/import for character sheets:
![изображение](https://user-images.githubusercontent.com/40369500/182478487-a6d9407d-fb49-4cbf-91e3-e7b22ce14667.png)

Also there is json export in the power's card and json import of powers in character sheet:
![изображение](https://user-images.githubusercontent.com/40369500/182478730-961e0758-b159-4129-84e7-268cdc151686.png)

Does it mean that you or anybody else has already made *.dnd4e (xml) to character's or powers' json converter?

![изображение](https://user-images.githubusercontent.com/40369500/182479233-324cb2b8-2f18-416d-8c64-9e7cd2bd4d68.png)

![изображение](https://user-images.githubusercontent.com/40369500/182479170-ac749f10-3692-40d7-9b47-403750aafbd4.png)

I can not find anything by search.

**Comment by draconas1** [comment]
There is no support to import from the character builder files directly into Foundry, nor is it a feature we plan to develop (due to immense complexity) sorry.
