### ISSUE TITLE
[V10] Objects with Effects kills the Character Sheet data

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#234]
Any item/feat/power with an effect cannot be on the character without it breaking:

It's possible I'm doing something wrong, but the effects I add (ie @data.resistances.cold.value -> Add -> 5) all worked v9. I expect this is known already, as its a pretty game-breaking one, but in case it isn't, I thought I'd share.

![image](https://user-images.githubusercontent.com/5306827/188231282-31c667de-035f-45a4-aa96-0f9cf3f38b70.png)

**Comment by EndlesNights** [comment]
In v10 the `@data` has been superseded by `@system` or even just simple `system` it should now be writen as `@system.resistances.cold.value` or `system.resistances.cold.value`

I totally forgot to write migration scripts to fix this, or warn people about it. My bad. Foundry by default has one is place what would have automatically fixed the effect if it had been written as `data.resistances.cold.value` without the @ prefix.
