### ISSUE TITLE
[v10] Can't open/edit some item (data type) types

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#236]
Since updating the Foundry 10 and later, I'm having an issue where I can't open/edit some types of items. Here's the error message from the console:

![image](https://user-images.githubusercontent.com/10067730/188295605-2187aa10-02e9-409f-aef4-375e19bd5821.png)
`TypeError: An error occurred while rendering ItemSheet4e 73. Cannot read properties of undefined (reading 'detail')`
`    at ItemSheet4e.getData (sheet.js:115)`
`    at async ItemSheet4e._render (foundry.js:4959)`
`    at async ItemSheet4e._render (foundry.js:5684)`

It happens for class/race/path/destiny features, feats, rituals, weapon and equipment items. Only powers and consumables seem to be unaffected. Seems to be true whether I'm editing from the sidebar, through a character sheet, of from a compendium.

In case it was a legacy issue, I tested with new items on a fresh v10 world with no modules enabled (aside from libwrapper) and got the same result.

**Comment by EndlesNights** [comment]
Should be fixed in the latest patch.

**Comment by FoxLee** [comment]
Confirmed. Thank you!
