### ISSUE TITLE
Issues with custom effects in V10

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#238]
Rogger has found an issue with custom effects in V10, it appears that the weapon is not being picked up for damage at least and some of the damage keywords are missing.  

When we debug the power searcher is not picking up the last damage keyword: thunder.  though it shows up fine on the damage dice display.  Have no idea about that one.  Possibly dropping the last for some reason.  
See the log:

- D&D4eBeta | Debugging damage effects for Booming Blade.  Supplied Weapon: undefined
- helper.js:173 D&D4eBeta | Found the following possible active effects
- helper.js:174 D&D4eBeta | Bonus : power.damage.thunder.feat = 3+@epic
- helper.js:195 D&D4eBeta | based on power source, effect type, damage type and (if weapon) weapon group, properties and damage type the following effect keys are suitable
- helper.js:197 D&D4eBeta | bladeH, damage, imp, psychic
- helper.js:211 D&D4eBeta | The following effects were deemed suitable by keyword filter
- foundry.js:4950 Foundry VTT | Rendering Dialog
- dice.js:390 ['((1 * 1)d8 + 6 + (1) + 0)[damage, psychic, thunder]']0: "((1 * 1)d8 + 6 + (1) + 0)[damage, psychic, thunder]"length: 1[[Prototype]]: Array(0)

`thunder` is missing despite it being a damage keyword.  Is weird.  

We also see in the damage calculation that the weapon is null, despite a weapon being used.
The weapon is picked up on the attack selection.  Suspect checking the difference between the attach call to the method and the damage call to the method will fix that.  

Am currently ill so will not be able to look at this until at least next week sorry :(

[power.json.txt](https://github.com/EndlesNights/dnd4eBeta/files/9508930/power.json.txt)

![Attack_log](https://user-images.githubusercontent.com/25391996/188957574-37e9cd76-dc1e-4097-9823-3ea4623f71b2.png)
![Damage_log](https://user-images.githubusercontent.com/25391996/188957583-4168785c-4a64-4ecf-949b-5660c3534867.png)

**Comment by EndlesNights** [comment]
Fixed in #239
