### ISSUE TITLE
Powers have lost damage keywords

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#246]
Not sure if this is paving the way for a new keyword display mechanic, or an unintended consequence of something else, but in case its missed: the damage keywords in the power descriptions (NPC and PC) are now gone.

![image](https://user-images.githubusercontent.com/5306827/193913950-8a1edb1a-fe05-4bce-929c-558294258b9f.png)

![image](https://user-images.githubusercontent.com/5306827/193914096-15add82d-5584-4d90-8064-a165ad3987e3.png)

**Comment by EndlesNights** [comment]
I see the mistake I made, I finally got around to allowing weapons to override the damage types of powers, and didn't properly update the labels. Thanks for the catch! Will be patched through asap!

**Comment by drywallmud** [comment]
No problem, but it seems the issue persists on my updated build (unless the fix update is still queued. Hard to know)
