### ISSUE TITLE
Translation - Add French Translation

### ISSUE THREAD

**Issue by Gilphe** [EndlesNights/dnd4eBeta#258]
Hi, 
I'm using your module for some time, and I enjoy it. I'm confortable with english, but my players don't, so I've start a french translation for your module. Basically, I've translate all the "lang/en.json" file for now, it's enough for the translation of all the character sheet and most of the forms. 
I would like to sharing it, and want to update it each time you will make some change to the en.json file. So if it's ok for you, I can push my file to your repository. Please find below the file i've made so far.

Have a good day, 
Regards,
[fr.zip](https://github.com/EndlesNights/dnd4eBeta/files/10544601/fr.zip)

**Comment by draconas1** [comment]
Have raised a PR for this against the current dev branch

**Comment by EndlesNights** [comment]
Merci beaucoup pour la contribution.
