### ISSUE TITLE
Unable to open character sheets on Foundry version 0.8.6

### ISSUE THREAD

**Issue by BioOnPC** [EndlesNights/dnd4eBeta#26]
Attempting to open a character sheet, including ones that are freshly created, returns an error and do not open.
![image](https://user-images.githubusercontent.com/25067089/120704808-0c3dc000-c485-11eb-9925-08624ba102de.png)

**Comment by EndlesNights** [comment]
This is probably because I have yet to update the system to support Foundry 0.8.X, something which I have started working on but as of yet have not completed.

Currently compatible Core Version still only extends up to 0.7.10.
