### ISSUE TITLE
Add concealment (and total concealment) as common effects

### ISSUE THREAD

**Issue by witchydiana** [EndlesNights/dnd4eBeta#260]
Hey, just a simple wishlist item: add concealment (aka partial concealment) and total concealment as common status effects for the token HUD, ~~Inkpot~~ module integration, and such. Lots of effects grant concealment and it'd be nice to have.

**Comment by FoxLee** [comment]
I wonder how hard it would be to allow a customisable conditions list? I'm currently using the entire Combat Utility Belt module just for the sake of customising my conditions (and their icons), which seems like using a hammer to swat a fly :|

For now, adding these two conditions is something I'd be happy to take care of. Will post again when I'm done!

**Comment by FoxLee** [comment]
Kay, I've filed a pull request with updates that address this. Hopefully you hadn't bothered to do it yourself yet :p

If you don't want to wait for main to update, please help yourself to the files!

**Comment by witchydiana** [comment]
Ah, much appreciated! Pardon the late reply, I hadn't yet attempted this myself, having been busy getting more effects and such plugged in for PCs

**Comment by FoxLee** [comment]
No worries! I've been tinkering with the game files a bunch lately, so this seemed like perfect low-hanging fruit to grab on the way through :)
