### ISSUE TITLE
Daily keyword in the french translation

### ISSUE THREAD

**Issue by BaptisteAdam** [EndlesNights/dnd4eBeta#262]
Hi
I have taken a look at the recently commited french translation.
I would suggest to use "Quotidien" instead of "Journalier" for the daily keyword as it's what is in the books.

**Comment by Gilphe** [comment]
Hi, 
Sure, ok for me. I've tried to tied to the book but surely everything is not entirely accurate. It's a good thing to review it. 
Thanks for the comments, I have update the file, please find below the new version. 
Also, I've had some lines into the _system.json file_, below the "language" bloc. With that, if you switch the language in foundry, it's automatically load the translation. 

[Open_Issue_262.zip](https://github.com/EndlesNights/dnd4eBeta/files/10674169/Open_Issue_262.zip)

**Comment by BaptisteAdam** [comment]
No problem, not everything needs to be perfect, I'm already ecstatic enough that a game system for 4e exist and that it's actively being developed. 

That said, I've taken a bit more look at the translation and I would suggest using "électricité" instead of "eclair" for the lightning damage type, because it's also what is used in the books. And because "dégâts d'éclair" is a bit weird to say ;)
