### ISSUE TITLE
[Proposal] Detailed typing for PCs

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#263]
Any problem with me adding origin/type/subtype fields to Player Characters? I know these are normally omitted from character sheets and left to the default of natural/humanoid, with any exceptions being expressed as a feature, but obviously PCs do have these properties "under the hood". 

Reason I'm bringing it up is, I've got 4e type detection implemented in fork of the Active Auras module, and this would allow it to select PC tokens as effectively as it does NPCs :)

**Comment by draconas1** [comment]
No objections here.  Given how rarely it comes up for a PC I would put the UI in the biography tab to avoid excess clutter.

**Comment by FoxLee** [comment]
Definitely what I was thinking yeh. Most people won't care about it so best to put it somewhere discreet.
