### ISSUE TITLE
[TRANSLATION] - Update French Translation (3.25)

### ISSUE THREAD

**Issue by Gilphe** [EndlesNights/dnd4eBeta#273]
Hi, 
I've update the file for the french translation of your module. 
Please find below the zip file containing : 
- lang/fr.json : Update translation for 3.25 version of your module
- system.json : Add a block to declare the fr file (in the language block)

Have a good week-end ! :)
[dnd4eBeta-fr-translation.zip](https://github.com/EndlesNights/dnd4eBeta/files/11001673/dnd4eBeta-fr-translation.zip)

**Comment by EndlesNights** [comment]
Thanks again! Added to the dev branch, and will be part of the next patch that comes out in a little bit. In the future do you think it is possible you could try making Pull Request? It would be a little simpler for me to incorporate changes that way.
