### ISSUE TITLE
[Feature Request] Death Saving Throws and Saving Throws cannot be fast forwarded

### ISSUE THREAD

**Issue by poketch** [EndlesNights/dnd4eBeta#276]
Right now Saving and Death Saving Throws rolled from the sheet always spawn a Roll Dialog. Is it possible to allow these to be fastforwarded with default settings similar to the other sheet rolls.

**Comment by EndlesNights** [comment]
A minor refactor later, and these can now be fast-forwarded. While I'm at it, I'll probably give some other buttons that don't have a fast-forward capability, such as the Short/Extended Rest buttons, Second Wind, and Action Point.

Currently this is only on the Dev branch, but I'll aim to push this patch through to the main sooner than later today.
