### ISSUE TITLE
[Suggestion/ Feature Request] Auto Fast Forward Rolls

### ISSUE THREAD

**Issue by poketch** [EndlesNights/dnd4eBeta#277]
Re: https://discord.com/channels/415906830137556992/800019673713606717/1088598842464813136

I'd be happy to submit a PR for this. 
My suggested changes would be registering a new setting `autoFastForwardRolls`

```js
settings.js

export const registerGameSettings = function() {

/* ... */

game.settings.register("dnd4e", "autoFastForwardRolls", {
    name: "Automatically Fast Forward Rolls?" ,
    hint: "When Enabled: Reverses the defaultroll behaviour. All rolls are fast forwarded and holding SHIFT/ CTRL/ ALT/ META will display the roll prompt"
    scope: "client/world",
    config: true,
    type: Boolean,
    default: true
});

}
```
Then, the desired behaviour is determined by the logical XOR of that setting and the operation of the current `isUsingFastForwardKey` helper function which I implement using a ternery operator

```js
helper.js

export class Helper {

/* ... */ 

static isRollFastForwarded(event) {
    const isModKeyPressed = event && (event.shiftKey || event.altKey || event.ctrlKey || event.metaKey);

    return game.settings.get("dnd4e","autoFastForward") ? !isModKeyPressed : isModKeyPressed;
}

}
```

Let me know if you want me to submit the PR.

**Comment by EndlesNights** [comment]
Thanks for the suggestions. added with patch 0.3.31
