### ISSUE TITLE
Make autogenerated power cards optional

### ISSUE THREAD

**Issue by mageofthesands** [EndlesNights/dnd4eBeta#28]
Foundry Virtual Tabletop 0.7.10  
4th Edition Beta 0.1.4

I recommend making the powercards that show up in chat that are generated automatically to be optional.  I suggest having a Default as set by the GM in System Settings, but have each actor sheet to have the option of turning it on or off.

**Comment by EndlesNights** [comment]
I just want some clarifications on if this is what you mean.
I'm adding a togglable option to every powers. If checked the power card portion of the chat message will not display in the chat message when the power is used. But other elements such as the Power Details, and the Attack/Damage buttons will still be their (Unless they are also disabled or empty)

See example below where the top image has Auto Generate Chat enabled, and the bottom message has it disabled. But none of the other parts are changed. so you still have the details text, and buttons.

![image](https://user-images.githubusercontent.com/58280840/121571548-2cbfca00-c9f1-11eb-92ca-aaff55ab1749.png)

**Comment by mageofthesands** [comment]
That's great.  It's working.  I would be great if there was an option to set a default so it doesn't need unclicked for every power.

**Comment by EndlesNights** [comment]
Added in a system option toggle for this now in 0.2.31
