### ISSUE TITLE
Foundry v11 : dnd4e 0.4.6 : System SVG does not have width and height defined

### ISSUE THREAD

**Issue by rikmarais** [EndlesNights/dnd4eBeta#288]
**Note**: Browsers handle the SVG issue differently. Chrome handles it but Firefox does not. This is upstream of Foundry, and the best way to ensure that it works is to make sure that the SVG itself correctly specifies dimensions as required by Foundry so as to not rely on the browser patching it. 

![image](https://github.com/EndlesNights/dnd4eBeta/assets/34374883/dae2d537-be30-402c-8ff2-b396f39e9ee5)

Not Forge specific but reported on Forge
https://forums.forge-vtt.com/t/foundry-v11-d-d-4e-and-forge/82456/2

![image](https://github.com/EndlesNights/dnd4eBeta/assets/34374883/0cfb5d02-9677-4421-a363-2cde6862a89f)
```
Foundry Virtual Tabletop: Version 11 Stable, 11.302
Game System: dnd4e, 0.4.6
Active Modules: 1
Performance Mode: 2

OS: Windows NT 10.0; Win64; x64
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Max Texture Size: 16384

No viewed scene

Actors: 0 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 6 | Chat Messages: 2
```

Likely related to https://github.com/foundryvtt/foundryvtt/issues/9052

**Comment by EndlesNights** [comment]
Interesting, we had some additional SVGs added a little while back where the height and width defined in the style. But it appears that not all browser can pull the dimensions data from their. Thanks for pointing this out, I'll edit the SVGs and have a fix out in a just a bit.

**Comment by TheNittles** [comment]
@EndlesNights Apparently the Dazed icon is having this same issue now? It was loading fine for me on firefox before but now I've got the exact same issue.
![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/fbdaf737-77c8-4e49-9982-527730b60016)
