### ISSUE TITLE
Effect Duration no Longer Selectable

### ISSUE THREAD

**Issue by TheNittles** [EndlesNights/dnd4eBeta#289]
After updating to v11 and 0.4.7, active effects no longer have a duration such as "until end of next turn" selectable from the drop down menu.

![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/5c559035-e9d9-4c35-a4b9-d2ef15eaa28d)

The drop down menu is completely blank, which then in turn registers all effects as passives. I can get the icons to reappear by putting basically anything in any of the other boxes, but nothing I can do seems to make the auto-tracking of duration work again.

Tested on Forge and Local clients, with every module except Libwrapper disabled, same effect.

**Comment by EndlesNights** [comment]
fixed in update 0.4.8
