### ISSUE TITLE
[Feature Request] Automatically Populate Effect Descriptions

### ISSUE THREAD

**Issue by TheNittles** [EndlesNights/dnd4eBeta#293]
(i brought this up on the Discord but just wanted to put it here so it didn't get lost in the chat)

so Active Effects now have this "Effect Description" box when you set them up. here i've filled it out with a description of the effects of Cat's Grace.

![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/7fc25ef5-6df9-41e4-a20f-9f7bcb2f5669)

however, when the effect is actually applied to a token, the Effect Description does not populate to that instance of the effect, so the tooltip in modules like Dfred's Effects Panel or Combat Carousel Tracker just has the name

![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/fd9f8084-f242-4683-9a06-858898795d93)
![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/abc931a7-d2e8-429b-8a63-b737947e9728)

if you manually edit the effect and put the description in, however, the tooltip works perfectly

![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/6b5a085a-05bd-41e2-93dc-c0850b617dc0)

i don't know if the effect description not being carried over is a bug, and if it's not i don't know enough about coding to know if it's technically feasible, but if it is, having this field auto-populate with data from the base effect would be hugely helpful in conveying information about effects.

**Comment by Marcloure** [comment]
+1 to this, would also be nice to take the name and icon of the base feature

**Comment by EndlesNights** [comment]
This should be working since #295. Just a late close.
