### ISSUE TITLE
Translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by PilotodeMouse** [EndlesNights/dnd4eBeta#298]
Hello! I'm a big fan of the DnD4e system, and I would love to see its translation into Brazilian Portuguese, my native language. I know there is a large community base here in Brazil, so I have translated the system and hope that my small contribution can be made available in this fantastic work. I'm very grateful for the effort in making this system a reality in Foundry VTT.

Here is the translation. :)
[pt-br.zip](https://github.com/EndlesNights/dnd4eBeta/files/12071609/pt-br.zip)

**Comment by EndlesNights** [comment]
Thank you very much for the translation, I hope this better allows others to play, and I hope you enjoy your games as well.

**Comment by PilotodeMouse** [comment]
I am extremely grateful for being able to collaborate with this simply incredible work of yours. Thank you! Thank you! Thank you!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado:sexta-feira, 11 de agosto de 2023 00:47
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [EndlesNights/dnd4eBeta] Translation to Brazilian Portuguese (Issue #298)


Thank you very much for the translation, I hope this better allows others to play, and I hope you enjoy your games as well.
