### ISSUE TITLE
@bloodied tag not working in formulae?

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#299]
cozycat raised a question on Discord about applying the Vryloka healing surge penalty while bloodied. We thought it should work with a formula of `-2 * @bloodied`, and the documentation seems to confirm that it would. However, while there are no error messages, we found it always seemed to evaluate to 0. I ran some tests (replacing `@bloodied` with a fixed value, and trying to modify other values with `@bloodied`, <strike>and trying it in attack rolls</strike>, in and out of combat) and appears that `@bloodied` is never the expected value of 1.

I've tried to sus it out myself, and I found the code where the replacement values are set up (looking at `helper.js` ln 397). But I can't see why it wouldn't work. Any thoughts?

Update: Okay the "not working in attack rolls" was wrong, it was just an embarrassing mistake with Steve and his dual strike. So it looks like this may be working as intended, and it shouldn't be expected to work in effects. I'm curious as to why other tags do though—like `@paragon` and `@lvhalf`. They all seem to be applied by the same code, so what am I missing?

**Comment by EndlesNights** [comment]
Turns out, the helper function was just never being called. Fixed for 0.4.14
