### ISSUE TITLE
[Enhancement] Consumables should use the same effects as power rolls

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#305]
Consumables should use the same effects (hit, miss, all, etc.) as power rolls, since they have an activation, target, etc.

Currently, they use the standard effects:
![image](https://github.com/EndlesNights/dnd4eBeta/assets/29084710/e8b7bb1e-058e-4436-97bf-3fce8f01dfcb)

But since consumables are used on a target, and often require an attack roll, they should use the same effects as powers do:
![image](https://github.com/EndlesNights/dnd4eBeta/assets/29084710/852154a2-834b-43d9-bf58-fd2287115abd)

**Comment by EndlesNights** [comment]
Make sense. I have the basis down, will be part of the next patch in a few day time.
