### ISSUE TITLE
[Request] +2 defense bonuses automated after second wind button on sheet

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#306]
Hopefully this is a simple one. Now that effects are here, is there a way to automate the +2 AC/Fort/Ref/Wil (until start of next turn) when you use the built in Second Wind button just as it auto heals and debits a second wind use? It seems like it should be there.

**Comment by FoxLee** [comment]
To be clear, effects aren't new, they've been in the system for ages :) It's only having them apply ongoing damage and prompt for saves that's new.

But yeah, we should definitely look into adding an effect to the built-in second wind. If I recall correctly, I'm currently work ing around it by making a Second Wind encounter power that does apply the bonuses, and setting it to use second wind as its required resource.

**Comment by drywallmud** [comment]
I've actually been using the effects for a while now, and I also made my own encounter power that does the +2 defenses. I just have players who insist on using the built in sheet button because its there.

Also, amazing damage over time update.
