### ISSUE TITLE
[Request] Option to add active effects to power user exclusively on a hit

### ISSUE THREAD

**Issue by absolitud3** [EndlesNights/dnd4eBeta#307]
The only option currently available for self-applied effects is instantly upon power use, regardless of hit or miss. As the title implies, an option to add effects to the user of a power only in case an attack hits would be greatly appreciated.

(Fox suggested I come here to make sure this feature request is recorded, so here I am!)

**Comment by EndlesNights** [comment]
This has been added in for when 0.4.26 go live in the next patch.
