### ISSUE TITLE
Crit rolls do nothing

### ISSUE THREAD

**Issue by mageofthesands** [EndlesNights/dnd4eBeta#31]
Foundry 0.8.7
4th Edition Beta 0.2.3

Clicking "Critical Hit" when rolling for damage produces no rolls.
![Crits 6 16 21](https://user-images.githubusercontent.com/81931767/122296113-a824ee00-cebf-11eb-8501-c560a75086cc.jpg)

Attached screenshot demonstrates what formulae is being used.

**Comment by mageofthesands** [comment]
[localhost-1623984898304.log](https://github.com/EndlesNights/dnd4eBeta/files/6674310/localhost-1623984898304.log)

**Comment by mageofthesands** [comment]
[holysymbolofpelor.txt](https://github.com/EndlesNights/dnd4eBeta/files/6674322/holysymbolofpelor.txt)

**Comment by EndlesNights** [comment]
Issue should now be fixed as of latest update.
