### ISSUE TITLE
[Request] Add condition descriptions to default conditions

### ISSUE THREAD

**Issue by TheNittles** [EndlesNights/dnd4eBeta#315]
A little bit ago, you made the system add effect descriptions to active effects, which means if a way to display the tooltip for a condition is installed (like DFred's Active Effects or Combat Carousel Tracker) is installed, that condition's description will be shown. This is fantastic, but it doesn't do anything for the default conditions applied when right clicking a token, only to conditions I can write an effect for, like a custom Effect applied by a Power. If the default, compendium description of a condition was added to these default conditions, it would make them have the same descriptive tooltips. Attached are images, if I wasn't clear enough.

This is an effect applied by a power. I've copy/pasted the description of immobilized from the compendium to it.
![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/966ef4b9-d91f-4522-b8a5-1324d41af19f)

The description shows in the tooltip, allowing quick reference!
![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/965581b3-b043-4684-9ae0-64c8e09b2ac7)

However when applying the effect from this menu, say if you're improvising an effect in the middle of a combat . . .
![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/d0286106-73e0-4e20-9474-a977648e420b)

That tooltip is a lot less helpful.
![image](https://github.com/EndlesNights/dnd4eBeta/assets/137443034/4f981f40-8009-4f15-a996-d173da9082f9)

If these default effects could have their descriptions updated with the journal entries of the effects, it would be an extremely nice QoL feature for people who use DFreds or similar modules.

**Comment by EndlesNights** [comment]
Will be included in the next patch.
