### ISSUE TITLE
Some damage rolls do nothing

### ISSUE THREAD

**Issue by mageofthesands** [EndlesNights/dnd4eBeta#32]
Foundry 0.8.7
4th Edition Beta 0.2.5

It looks like clicking attack rolls for implement powers does nothing.  Damage formula for non-weapon rolls isn't working either.   For example, Infernal Wrath's damage formula of "1d6 + @chaMod" used to produce a roll of 1d6 + 2.  Now it does nothing.    I swapped it out for Sacred Flame's roll of "1d6 + @powerMod + @wepDamage" and still nothing.  Sacred Flame works fine though.  I tried to give Infernal Wrath an attack roll, but it's attack roll wouldn't work either.  Then I tried placing the "1d6 + @chaMod" for Sacred Flame, and it works fine.  I tried changing them around to different action types, use types, ranges, giving Infernal Wrath a weapon, limited uses to Sacred Flame.  Nothing changes.  Healing Word is the same way.  
![non-attackpowers](https://user-images.githubusercontent.com/81931767/122449759-d6f89e00-cf6b-11eb-9802-c5fa36c70e42.jpg)

**Comment by mageofthesands** [comment]
[infernalwrath.txt](https://github.com/EndlesNights/dnd4eBeta/files/6673910/infernalwrath.txt)
[sacredflame.txt](https://github.com/EndlesNights/dnd4eBeta/files/6673911/sacredflame.txt)

**Comment by EndlesNights** [comment]
Issue should now be fixed as of latest update.
