### ISSUE TITLE
[wishlist] Add secondary vulnerability and resistance attribute keys to implement 4e stacking rules

### ISSUE THREAD

**Issue by witchydiana** [EndlesNights/dnd4eBeta#327]
Heya, a hopefully relatively simple wishlist item: you know those wicked power.attack.implement.feat style attribute keys that apply 4e stacking rules? What about extending that to damage resistances? 

For instance, `vulnerability.cold` could be modified by multiple effects, and it would take the highest of them and apply that to the existing `system.resistances.cold.value`

I'm right now in the oh-so-fun situation of having multiple party members who have built into cold damage exploring the Glacial Rift of the Frost Giant Jarl, and managing whose Lasting Frost active effect is active or disabled is a mild PITA. Because some foes have things like temporary cold resistance effects, upgrade and downgrade active effects don't seem like the way to go. 

Some edge case powers that increase a vulnerability/resistance if the creature is already vul./resist. to that type could use the existing attribute key to bypass the stacking rule.

**Comment by EndlesNights** [comment]
Thank the Fox!
