### ISSUE TITLE
Contribution Request: Implementing multi-target attack rolls

### ISSUE THREAD

**Issue by ahoward-cf** [EndlesNights/dnd4eBeta#33]
I wanted to see if I could add a multi-target feature to attacks for use with Area Burst, Close Burst, etc. After forking the repository, I have been partially successful, though I admit, not fully (as it does not yield the attack button after all the rolls).

I have a few more ideas I would like to try, but I am new to JS/HTML/CSS (though proficient in other languages, so the core concepts are there). Therefore, I thought I should submit this as an issue, to start a dialogue before I attempted to submit a pull request, so that I can see if you are open to my contributing in general, and if you might be willing to help me understand where my multi-target method is failing. 

To clarify, my method gets the number of currently targeted tokens. If no tokens are targeted, it instead gets a value of 1. Then, within entities.js, it calls the roll function a number of times. This is crude, but effective. It works, but the attack button stops working after that - I think because it is waiting for more than one return.

**Comment by ahoward-cf** [comment]
I was able to fix my issue, so I now have the attack roll correctly counting the number of targets, or defaulting to 1 rolls, and correctly yielding the attack button after all rolls are complete. 

Therefore, I would really like to discuss collaborating on this project, at least to submit a pull request for this feature.

**Comment by EndlesNights** [comment]
This is something that has been on my todo list for a while. I'll take a look at your changes and would be happy to do a merge.

**Comment by ahoward-cf** [comment]
Wonderful. I submitted a pull request - branch was based off of dev which seems to be the most up to date. Though the changes should merge well with master too, as I don't believe they touch on the differences between the two branches.
