### ISSUE TITLE
Past skill training checks are gone, past values are untogglable

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#330]
So my characters all have their old skill values, but their checkmarks are gone. To add the checks, it only adds +5 again.

![image](https://github.com/EndlesNights/dnd4eBeta/assets/5306827/7f64175e-7c95-4d01-8564-530a8f773996)

**Comment by EndlesNights** [comment]
Just reading over everything again, there was a small error in a late addition of the the migration script that was causing the process to hang so nothing was being changed. I put out a hot patch that should fix the issue.

**Comment by drywallmud** [comment]
I AM using training on monsters, and it appears that that is fine. I'm not sure about before the fix.

![image](https://github.com/EndlesNights/dnd4eBeta/assets/5306827/f17e5da1-578c-4b76-aae2-31368fc8fcc6)

**Comment by drywallmud** [comment]
I'm going to close this issue, as it is no longer relevant.
