### ISSUE TITLE
[Bug] New Effect Application Timings not working for players

### ISSUE THREAD

**Issue by TheNittles** [EndlesNights/dnd4eBeta#340]
I have a power set up to Affect Self if Hit Targets. It works great when I roll it as a GM, but if my player rolls it, or if I roll it from an account in player mode, no effect. I tried it from a player account with my GM account logged in and still nothing. I also tried "apply after attack" and same story, works fine when rolling as GM, but not when rolling as player.

**Comment by EndlesNights** [comment]
Thanks for the report, just wrote a hot fix for this and patched it in.
