### ISSUE TITLE
[Request] Shield Bonus as defence modifier

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#344]
If possible, could we get a modifier that can be added with effects that uses "shield" as it's value. Example system.defences.ac.shield so we can assign a shield bonus with effects on feats and features such as hafted defence that will properly not stack when not applicable?

If this already exists, could someone explain how to do it, because I am struggling.

**Comment by EndlesNights** [comment]
Thank the Fox!
