### ISSUE TITLE
[Bug] Power Card Headers and coloring

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#348]
After the update about an hour ago, the power cards have very large headers. Unsure if it's solely the system, or a combination of the system and FoxLee's styling module. It was working fine with the module before updating to the recent system update though.

**Comment by NuptupTDOW** [comment]
Nevermind literally all of that. I turned off the module and turned it back on and it all just fixed itself. No idea what happened there.

**Comment by NuptupTDOW** [comment]
After resetting the module and confirming the system has fully updated and migrated, the only issue that still persists is the one above, with the powers having really big header portions.

**Comment by FoxLee** [comment]
It's not a system problem, it's just that a bunch of underlying names have been updated, so I need to update my styling module to match. (Don't forget, you can always turn off my styles to see if it's a system issue or not!)
