### ISSUE TITLE
[Request] Triggerless Effect

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#349]
Is there a way to store an affect on a power/item that will only show up as a chatlog button?

The use case is broader than this, but I'm thinking for things like: 

Capturing grab: 1d6 + 5 damage, and the monster makes two basic melee attacks. If both basic melee attacks hit, the target is grabbed and takes -2 penalty to all defenses.

If there could be an effect on that power that doesn't trigger, but is still stored on the power to be a chatlog button, it would be super handy.

I hope I'm making sense.

![image](https://github.com/EndlesNights/dnd4eBeta/assets/5306827/09a10ef2-c892-4642-a4d5-35b73bd968aa)

Thanks again for all your amazing work!

**Comment by EndlesNights** [comment]
Sure, we could add in a "None" or "Manual" or "Misc" category. Not certain on the name.
