### ISSUE TITLE
Item Weight Sum Broken

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#35]
There seems to be unpredictable results with the weight sum. 
(This was noticed prior to today's update, but sometime after Foundry 0.8.7)

![image](https://user-images.githubusercontent.com/5306827/123859123-82491180-d8e1-11eb-96dd-d35d93d079b1.png)

**Comment by EndlesNights** [comment]
I see the issue, part of the data structure change between 7.x and 8.x. Thanks for pointing it out should now be working again.
