### ISSUE TITLE
Some "weapons" shouldn't require a hand setting

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#354]
I may be about to open up a can of worms, but here goes; at the moment, slotless "weapons" like holy symbols and ki focuses have to take up one or more hands, by virtue of there being no none/slotless/worn/whatever setting in the weapon-hand list. I know the system doesn't enforce the number of hands available, but it really bothers me to have to put a slotless implement in a hand.

Would it be difficult to implement a "none" hand for such items? I feel like it should be possible, since the equipped toggle is separate to the hand setting, but I also know that the main/off hand setting helps determine weapon selection when you fire off a power. On the other hand (heh) none of the slotless implements are weapons, so I feel like this shouldn't come up unless there are powers hiding out there with "weapon or implement".

I'm hoping it's as simple as it seems, but I haven't really worked with that part of the system before, so floating it here in case there are complications.

**Comment by draconas1** [comment]
I think you are good, but its been a while since i was in that code.
