### ISSUE TITLE
Can't Edit Damage Resistance

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#362]
When creating new characters, damage Resistance Base column is blanked, and edits won't save: 

![image](https://github.com/EndlesNights/dnd4eBeta/assets/5306827/0f6ed177-b144-4157-a573-f81353803e97)

I should add I'm not updated to V12.

**Comment by FoxLee** [comment]
Looks like I hecked up resistances for NPCs specifically; no problems on player characters, but even through effects, NPC resistances/vulnerabilities are zeroed. Can you confirm that's what you're seeing too?
