### ISSUE TITLE
[Request] Money sum (value in gold)

### ISSUE THREAD

**Issue by WilliamTDoran** [EndlesNights/dnd4eBeta#366]
A simple thing, but it would be really convenient if the inventory screen provided a sum of what the value-in-gold of all the currency held by a player character is.

**Comment by EndlesNights** [comment]
Sure how about a tooltip over the Currency label that read out such as:
![image](https://github.com/EndlesNights/dnd4eBeta/assets/58280840/2aa50816-46b6-4bc8-a097-5d469fc58a73)
