### ISSUE TITLE
Fast forward rolls generate broken promise error

### ISSUE THREAD

**Issue by ahoward-cf** [EndlesNights/dnd4eBeta#37]
- dnd4eBeta v.0.2.13
- Foundry v.0.8.8
- **When:** holding `ctrl` , `alt` or `shift` when clicking Chat Card Attack and Damage buttons. 
- **What:** any and all attempts at a fast forward roll, with any power, item, or similar, result in a console error of a broken promise.
- **Additional:** not entirely sure of the purpose of fast-forward, beyond making a roll advantage or disadvantage. Had assumed it would roll the attack/damage without displaying the additional dialogue box, and with no situational bonuses applied. However, this does not appear to be the case?

**Comment by EndlesNights** [comment]
The fastforward option has been fixed to work properly in the next update.

The fastforward option is inherited from the initial forking from the 5e System (hence the references to advantage /disadvantage in the unedited documentation). The purpose of it is very much to roll the attack/damage without displaying the additional dialogue box, and with no situational bonuses applied.
