### ISSUE TITLE
V12 Start of turn ongoing damage activates for all players

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#385]
I've tried to test this locally, but trying to have multiple local connections appears to completely screw the socket system, all sorts of weird behaviour and effects triggering on unexpected turns. 

This makes getting a reprod case difficult as it will probably require 3 computers, DM, players 1 & 2.

But all my players reported that when an ongoing damage effect triggered at the start of a players turn (and they output their ongoing damage correctly to chat), all the other players got an error "you do not have permission to send a chat message" and "you do not have permission to edit that token" (or to that effect, chaotic bug reports in the middle of a session.  Which was implying to me that the auto-damage trigger was triggering for everyone, not just the target player and GM.

**Comment by drywallmud** [comment]
I can confirm my player's also see the "USER lacks have permission to send a chat message" chat message symbol pop up randomly during the start of a turn. This happens frequently for us. We also see damage get applied twice at times, and the damage log write the damage on the log two or three times.

**Comment by FoxLee** [comment]
Broke out the household's various laptops and did a test for this today, so I can confirm I'm seeing the same kind of mess as you both. As to why it's happening (and how long it has been a problem!) I'm still very much in the dark! I have one idea to test out tomorrow, but if that's a bust I'm feeling very clueless.
