### ISSUE TITLE
Burst/Blast template breaks rectangle template

### ISSUE THREAD

**Issue by WilliamTDoran** [EndlesNights/dnd4eBeta#386]
When using the provided Burst and Blast templates, after using them once, it causes the default Rectangle template to draw improperly. It no longer correctly snaps to the grid, and doesn't correctly follow the mouse. This doesn't affect the circle or cone templates.

The issue is per-scene, and persists until either leaving and rejoining the scene (even if the placed burst/blast is still in that scene), or reloading the world.

In this picture, the mouse cursor is roughly located where the pink circle is drawn.
![misaligned](https://github.com/user-attachments/assets/66e20fab-1f14-4b5d-97e9-dec20420c4ba)

**Comment by EndlesNights** [comment]
I see the issue, just needed to clear a flag that was being set to help the system specific templates.
This should be fixed in the next up coming patch 0.5.10. Thanks for the report
