### ISSUE TITLE
Resistances showing on character sheets, but not subtracting damage during damage application

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#390]
![image](https://github.com/user-attachments/assets/c2bb5847-aebc-4698-bc15-a2ee3a23ec6c)

using standard @system.resistances.fire.res ADD 2, but its the same across all resistances (armor resistances for instance)

**Comment by drywallmud** [comment]
I should add this was noticed BEFORE the last update. My bad for not reporting it, I wanted to make sure it wasn't a goof on my part before I did.

**Comment by FoxLee** [comment]
I finally have a lead on this! It looks like it's specifically a problem with damage typing from chat cards. At some point before it gets calc'd, the selected damage typing is being dropped and reverted to `damage`, which bypasses all typed resistances. This can be checked by adding Resist All to the character, the only resistance that applies against the `damage` type. (Would love you to confirm that, if you can!)

Now we just have to work out _why_ the typing is being dropped. Will update again when I find out more!

**Comment by FoxLee** [comment]
Sussed it out! The property containing the damage type has moved, so the helper that processes chat card damage needed updating. I think this should have it sorted.
