### ISSUE TITLE
Token Action HUD stopped working after upgrading to Foundry v12

### ISSUE THREAD

**Issue by Leeder87** [EndlesNights/dnd4eBeta#392]
After upgrading to Foundry version 12 and the latest version of D&D4 system, the Token Action HUD module stopped working. I tried different browsers, but none is showing.

Versions:
Token Action HUD Core: 1.5.7
Token Action HUD Classic: 3.0.21
System: D&D 4th Edition version 0.5.4
Foundry VTT: Version 12 build 331
Browsers: latest Firefox, Edge, Chrome

**Comment by FoxLee** [comment]
Are you remembering to also run Drac's 4e tools? That's still where the integration for TAH is AFAIK.

By listing both TAH Core and TAH Classic, do you mean that you have tried each separately, or that you are running them together? I wouldn't expect either one to work if you are running both at the same time. You should only need Core if you're on the latest versions of the system and Drac's Tools.

**Comment by Leeder87** [comment]
Hmm, I don't think I ever used Drac's 4e tools. I'll give it a try.

Yes, I tried Classic alone, Core alone, and both of them at the same time. None of the combinations works, although before Foundry v12 I used only Classic, and it worked.

**Comment by FoxLee** [comment]
Checked this out after finally updating to v12. Looks TAH Core changed their default styling so even with Drac's integration, it does not look as it should right now. I've flagged it with Draconas, and if they can't work on it right now I might try to help out after I'm done with the other system bugs I'm hunting right now.

**Comment by draconas1** [comment]
Yeah custom styling is bust.  Currently the Drac's tools works with TAH Core 1.5.x

I will push a quick fix version by the weekend that works with 2.X, but have not been able to fix the style issue so far.

**Comment by draconas1** [comment]
There is now a new handler: https://github.com/draconas1/token-action-hud-dnd4e

The installation instructions will link you to the correct version for your version of Token Action HUD

You also want to update to the latest version of Drac's Tools.
