### ISSUE TITLE
Correct version of Token Action HUD?

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#394]
I was wanting to know which version of Token Action HUD is the correct one to be using with an up-to-date foundry and dnd4e system install. I know there was a change from TAH Classic to a custom TAH 4e for a while, then I believe the change was made to support TAH Core+dnd4e but I just can't seem to figure out which is the correct option since the current TAH 4e says it's for TAH Core 1.5, but TAH Core is on 2.0.x now, and it doesn't have compatibility. Again, I'm not really sure which is the proper version of TAH to use for the 4e system, and until other options are supported (#382) TAH is still the most convenient option for most groups. So, if there could be a bit of clarification made on this until there's an opportunity to work towards #382 it would be great. I currently have a back-installed 1.5.7 TAH Core to use with the current(?) TAH 4e, but I'm not sure if that's the correct method.

Thanks again for all the support!

**Comment by draconas1** [comment]
If you have Token Action Hud Core 1.5.x then Drac's Tools includes the latest 4e integration point.  AFAIK Classic is dead, Endless did a custom fork at one point to fix a bug but I don't think that is being maintained.  

I will get around to updating it to 2.0 soon - I don't think there are any changes and you can manually edit the constants file if you want to go to 2.0.x

**Comment by draconas1** [comment]
There is now a new handler:  https://github.com/draconas1/token-action-hud-dnd4e

The installation instructions will link you to the correct version for your version of Token Action HUD
