### ISSUE TITLE
0.5.5 Update: Can't apply damage with a situational bonus value added

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#398]
There is no damage subtracted from HP when you click "Apply Damage" or "Apply Half Damage" on the chatlog when a situational bonus value is added.

Clicking the damage buttons on the chat log will still properly show "You must have a token selected to apply damage" if token is not selected.

Edit: Sorry, misdiagnosed the issue to be damage related earlier when it was situational bonus related.

**Comment by drywallmud** [comment]
I should add clarification: I tried applying 55 fire damage on a 30 fire resist azer. No damage was subtracted.

I just tried normal damage on a minion and everything worked fine.

**Comment by drywallmud** [comment]
Also: Untyped damage works fine.

**Comment by EndlesNights** [comment]
Thanks for the catch, added in a safety operator to the function that resolves the issue.
Hotfix on the way!

**Comment by drywallmud** [comment]
Awesome! Thanks for the speedy fix!
