### ISSUE TITLE
[Feature Request] Ability to manually add Status Effects to Actors

### ISSUE THREAD

**Issue by Fattyki** [EndlesNights/dnd4eBeta#40]
Not sure if it possible or not, but it would be great if Status Effects could be manually added to Actors.

**Comment by ahoward-cf** [comment]
Could you explain that a little bit more? 

Do you mean named markers on the tokens (so you can visually see which ones are slowed, stunned, etc), or do you mean a tab or section of the character sheet where you can add conditions which actually affect stats (I think this might be planned, with passive and active "effects" which are not in there yet), or do you mean both (placing a marker on the token applies the effect to the character sheet, and applying an effect to a character sheet marks the linked token), or do you mean something different?

Is there a system that does what you are thinking of that you could reference?

**Comment by Fattyki** [comment]
I am referring to the character sheet where you can add conditions.  Please see pic below:
![Snag_6fae8f9](https://user-images.githubusercontent.com/87339685/126018770-3159d0ac-c8d0-4a16-9e65-a9f065f1a0e7.png)

After investigating the workflow of assigning a status icon on the token from the token by right clicking, I then noticed that it showed up underneath the character sheet.  From there I could edit duration of the effect.  

It sounds like doing it from the character sheet side first is planned for later?  Being able to do the workflow from both starting points would be nice.

I should also add that I really like the mouse-over callout when selecting the status from the token.   A mouse-over callout of a particular token that showed the currently active status conditions would also be lovely.

**Comment by EndlesNights** [comment]
Just missed updating a line of code when going from 7.x to 8.x. Should be fixed the next coming update.
