### ISSUE TITLE
Broken Ruler on Gridless Maps

### ISSUE THREAD

**Issue by warforged44** [EndlesNights/dnd4eBeta#400]
I noticed an issue where the ruler (whether using the core ruler tool or something like Drag Ruler) fails to show an accurately measured distance on gridless scenes. It just locks at the scene grid size as shown below:
![image-3](https://github.com/user-attachments/assets/11c03093-e799-43c7-83a9-3f795f4f223d)
![image-2](https://github.com/user-attachments/assets/fe8c2759-9740-44a2-a2ab-657fd77394e3)

I didn't have the issue in v11, being able to measure distances to scale on gridless maps.

As far as I could tell from my testing, the issue is only present in Foundry v12 in the dnd4e system with libWrapper activated. In case it's helpful information, I tested the following:
- Foundry v12, dnd4e, all my usual modules: broken ruler
- v12, 4e, no modules: functional 
- v12, 4e, only libWrapper: broken
- v12, 4e, all my modules except for libWrapper and those that depend on it: functional
- v12, different game system, libWrapper and others: functional

**Comment by EndlesNights** [comment]
This should be fixed in the next up coming patch 0.5.10.
