### ISSUE TITLE
Non-weapon attacks don't roll Base Damage dice

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#41]
When a power has 'Weapon Required' set to [None] [None], and the Base Damage is set to a dice variable, the attack does not roll from '@powBase'.

This may be a 'not done yet' feature, but on the chance its overlooked, I'd like to bring it to your attention.

Thanks for all your work on this amazing DND4e system.

**Comment by EndlesNights** [comment]
Issue will be fixed with version 0.2.26
