### ISSUE TITLE
Where do you get the JSON for power imports? 

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#44]
I feel like I'm going to feel really dumb as soon as I get the answer, but it's been a while since I've been a part of the 4e microcosm, so I am blanking on how to get it...there's like a website right? I don't think its iplay4e, but maybe a different one?

Edit: So, I'm sure I could use something that format's JSON output based on a text editor. I'm just thinking there was a site I could import my CBLoader file into and it'd output necessary JSON after running the CBLoader file through details adder. Am I just losing my mind?

**Comment by EndlesNights** [comment]
No need to feel dump or silly. I just wanted to make it easy for users, including players who might have limited permissions within their Foundry game to input/export powers easily.
There is no website or any place that is a repository of powers/items that are Foundry 4e compatible. Such places could be made by others, as I don't have much plans other than making some simple example powers for a compendium to include in the system.

No need to loose your mind.

**Comment by NuptupTDOW** [comment]
> I don't have much plans other than making some **simple example powers for a compendium** to include in the system.
> 
> No need to loose your mind.

Is this already in the current version of the system? I checked the compendiums tab and didn't see it. If not, that's totally fine, just wanted to know is all.
