### ISSUE TITLE
Weaponless max damage on crit rolls.

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#45]
Thanks so much for the earlier feature/fix with @powBase on weaponless damage! Can you extend the functionality to @powMax?

When a power has 'Weapon Required' set to [None] [None], and the Base Damage is set to a dice variable, the attack does not roll maximum die/dice value from '@powMax'.

Cheers!

**Comment by EndlesNights** [comment]
Small oversight on my part, Fixed for dev 0.2.27
