### ISSUE TITLE
Power's base die number ignored by critical hit powMax formula?

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#47]
In powers that use a [W] multiplier higher than 1, it seems that multiplier is not used correctly in critical damage—at least in the default formula using the powMax value. I get the correct output from the damage formula for a normal hit, but if I roll a critical hit—using powMax instead of rolling the power's damage—it seems to use 1 * [W] regardless of what the power's base damage is set to.

I realise I can work around this by manually multiplying powMax in my crit formula, but assume powMax would be intended to include the power's base [W] multiplier.

[**EDIT:** Sorry, it's not just [W] multiplier, it's the power's base die number in general. So for example, on a power that does 2d8 powMax instead uses (1 * 8). I changed the title to reflect this.]

![image](https://user-images.githubusercontent.com/10067730/132112443-6abc8d6e-9191-46b9-8812-7227a33420fb.png)
![image](https://user-images.githubusercontent.com/10067730/132112481-439a31ad-2cf0-4bb1-aff5-b00e4bc7117e.png)

**Comment by EndlesNights** [comment]
Issue should have been properly addressed now in the latest patch.
