### ISSUE TITLE
If power has description deleted, "null" text left.

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#48]
By no means a deal-breaking bug, but I figured I'd report it.

![image](https://user-images.githubusercontent.com/5306827/132140210-7d58c7e8-24d0-4137-9a7c-10a55a138bdb.png)

**Comment by EndlesNights** [comment]
Well how about that, never noticed that one before. This issue is even within the 5e system as well. I'll be sure to let them know as well as the simple fix for it.
Thanks! This will be fixed in the next patch v0.2.28 which I will push later today or tomorrow.
