### ISSUE TITLE
[Feature Request] Added Effect Types & Keywords

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#50]
Could you add the following effect types & keywords to the power template? I've come across a few powers that use them.

![image](https://user-images.githubusercontent.com/5306827/133866605-f05a3376-f83c-441b-9467-7e2d3788d8b9.png)

Gaze
Mount
Disease

**Comment by FoxLee** [comment]
Other extant keywords that are not currently available (excluding power source and damage type keywords as these are assumed to be applied automatically):
- Channel Divinity
- Aura
- Full Discipline
- Augmentable
- Runic
- Elemental
- The Essentials magic school keywords (Nethermancy, Necromancy, Evocation, Transmutation)

**Comment by EndlesNights** [comment]
Thanks a lot you two, I'll included all of these for the next patch, and some time in a future I'll also see about adding a text line where users can just type in their own keywords as well.
