### ISSUE TITLE
Initiative tiebreaker should use inititiave modifier, not dex mod

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#52]
If I understand correctly, the initiative tiebreaking mechanic is currently none by default, and dex mod if enabled under special rules.

In 4e, using tiebreaking is the core rule, and it's based on total initiative modifier, not dex mod:

"Ties: When two creatures have the same initiative, the one with the higher initiative modifier goes before the other. If their modifiers are the same, their players can roll a die or flip a coin to break the tie." (Rules Compendium pg192)

So it would be more accurate to have "no tiebreaker" be the optional rule rather than the default.

Even if tiebreaker is not the default, the value checked should be changed from dex mod to initiative mod.

**Comment by EndlesNights** [comment]
Thanks for the point out, this should be fixed in the next main branch update.
