### ISSUE TITLE
Errors in power range/shape descriptors

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#53]
**Melee:** Some 4e powers have a range of "Melee x" but are not weapon powers. This is very common for monster abilities, but also occurs in some player character powers. (Example: the Monk's various Flurry of Blows powers are Melee 1 or Melee 2.)

This doesn't seem to be available in the current ruleset; I can only select Melee Weapon, which would be incorrect for these powers (and would cause some undesirable effects like adding the weapon keyword to the auto power card).

**Wall:** Wall is a shape—like burst/blast—and thus should be prefixed with area or close rather than being on its own. So "Wall" range should be replaced with "Area Wall" and "Close Wall" options.

Area Wall should also have the "Shape x within y" format that is currently only available for Area Burst. For example, the _Wind Wall_ power from _Heroes of the Feywild_ (pg 79) has the range "Area wall 8 within 10 squares".

**Touch:** Like wall, touch only appears as modifier to a range prefix. "Melee Touch" and "Close Touch" powers exist, but "Touch" does not occur on its own. (I could be wrong about this—I haven't exhaustively checked every power—but I believe it's correct.)

**Area Blast:** Area Blast should also have the "Shape x within y" format that is currently only available for Area Burst.

**Comment by draconas1** [comment]
For doing monster imports I added a pull request that does Melee N and Reach N as those were frequently on monster powers

**Comment by FoxLee** [comment]
There is a close wall power, the Warlord's "Form a Line" (Martial Power, page 88). It seems to be the only one, but that's a core book, so I would consider it important to include.

More surprisingly, I also found a close touch power; the Warlock's "Rending Fear of Khirad" (Dragon Magazine 366, page 22). It also seems to be the only example, but I guess one should include it if Dragon Magazine material is supposed to be fully supported.

Even if all touch is melee, the language of "Melee Touch" rather than "Touch Range" is important  because it makes it clear that a power should be counted for effects that relate to Melee attacks (e.g. Iron Armbands of Power).

**Comment by EndlesNights** [comment]
Alright I'll modify things to include them, and you are correct as the wording/language is indeed important for how interactions play out such as AoO, and so on.

That said I think Rending Fear of Khirad might be a misprint of so kind, because `Close Burst 1, Target: One whatever` are quite common and based on the other conditions of the spell it would very much still work out mechanically the same way. I'll still include Close touch because why not.

**Comment by FoxLee** [comment]
Yeah, I think either one might make more sense with a different "shape"... a lot of the Dragon Magazine stuff (in particular) is a bit wobbly on rules templating. But, I assume community errata is outside the scope of this project, certainly as far as just getting the ruleset complete goes.
