### ISSUE TITLE
Blank Power Source results in "undefined" in power card

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#57]
If the power source is not selected the power card shows "undefined" as the power card helper always performs the lookup against the config object even if the user has not selected a power source.

Power sources are rarely available for monster powers, and are not available for any in Masterplan.

Have raised a pull request with a fix.

**Comment by EndlesNights** [comment]
Thanks for the Pull request. I've been meaning to get this done and it just kept putting it off.
