### ISSUE TITLE
Add "Melee" and "Reach" options to range

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#59]
Monster powers specify their melee attacks in terms of Melee N and Reach N rather than referring to a specific weapon.  Even when the monster is using a weapon and power named after it they do not always follow the regular stats of that weapon.  

A feature request to added Melee and Reach as range options.

I have submitted a pull request for this.

**Comment by EndlesNights** [comment]
Thanks for the pull, just had to also add in small change so that the header will also show these additional options. It's all working great!
