### ISSUE TITLE
Missing Leader Option in NPC sheet

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#61]
Some Monsters have a Leader classification which would normally be an addition role flag as it combines with all roles and all subtypes save Minion.  

Can this be added to the NPC sheet and template?  Currently I am using `leader: boolean` in the role object for the importer but will happily change it to anything you prefer

**Comment by EndlesNights** [comment]
I'm just trying to think about the best way to implement a Leader tag onto the sheet without adding in more clutter. I'm not too sure about using a boolean, and including a check box with a Leader Label next to it. Instead I'm considering just doubling the number [creature options](https://github.com/EndlesNights/dnd4eBeta/blob/main/module/config.js#L283), and have a copy of every role just also followed by `(Leader)`. 

Would that work with what you have planned?

**Comment by draconas1** [comment]
So it can work for me, as its just a permutation to output.  

The risk is it makes things more complicated for anything in the sheet that wants to care about monster role as it now needs to care about 2 different role values, nothing I have cares currently as all my workings that care about that happen at the point it is marshalling the data.

**Comment by EndlesNights** [comment]
That is another valid concern, I will be going with the boolean toggle for now then.
![image](https://user-images.githubusercontent.com/58280840/136096755-82affd24-71d9-460b-b695-55d24e3128d4.png)

**Comment by EndlesNights** [comment]
Alright then, pushed through the dev branch. And should be merged into the 0.2.39 patch when I get around to it.
