### ISSUE TITLE
Advanced Math Option doesn't work on import

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#62]
Sorry, no pull request for this one as I have no idea how to fix it properly
[sample.txt](https://github.com/EndlesNights/dnd4eBeta/files/7273577/sample.txt)
:

I have 2 issues around the Advanced Maths Option for NPC's:

This is when creating an NPC using:
`await Actor.create(
                    {
                        "name" : creature.Name,
                        "type" : "NPC",
                        "data" : creature.Data
                    }`

Firstly if `advancedCals` is set in the creatures data object it is ignored completely.
Secondly the "auto turn on NPC advanced calculations" does not set the field.

Repo case:  I have attached a sample json for creature data that you can use to test.  

Investigation:

I put some debug statements in Actor4E's constructor:
Firstly it appears to be called twice for each time Actor.create is called.  The first time it has the `advancedCals: true` property set in its data object, the second time it runs that field is now undefined.  I have no idea why it is being called twice, or what has happened to the field.  Possibly because it is not part of the template?

For the second time the code runs where the field is undefined the "set to value from options" runs.  this sets `this.data.data.advancedCals` which does not appear to do anything - the field is still undefined when you investigate the actor object afterwards.  I changed this to `data.data.advancedCals` and it worked and the field was set.

**Comment by draconas1** [comment]
[sample.txt](https://github.com/EndlesNights/dnd4eBeta/files/7273583/sample.txt)

A sample data block to import

**Comment by draconas1** [comment]
I now have a work around for this so is less urgent (I call `actor.update({"data.advancedCals" : true})` after creation)

**Comment by EndlesNights** [comment]
Found the issue on my end, within the template.json it was instantiating `advancedCals` at `data.details.advancedCals `, while it's always used at `data.advancedCals `. The template should be fixed from the next update.
