### ISSUE TITLE
Nowhere to record Recharge condition for recharge powers

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#63]
There is a property in the template for recharge conditions, but it is not exposed anywhere on the UI

Have added a pull request for it

**Comment by EndlesNights** [comment]
Thanks for the Pull Request. In later version I will be looking into getting the recharge automation to function. And having it set on different modes such as `Recharge rolls` (which do make the majority of cases), and `Recharges when...` where some of the condition such as `recharges when blooded` can easily be tested and accounted for, but conditions would require input to be integrated manually by users in other ways.
Such as The Frostshaper's Icy Burst power, where it recharges when it hits with a melee attack. So its Ice Blade attack would need macro code inputted that could check if the attack hits, and then reset the charges on Icy Burst.
