### ISSUE TITLE
[Feature Request] Basic Attack Flag in Powers

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#65]
For NPC's one of their melee/ranged powers will simple be flagged as a basic attack unlike players where it is a specific power.

At the moment for importing I am using a boolean field `basicAttack` in the power data and setting a different icon to try and indicate this as some monsters have multiple melee/ranged attacks and being able to find the basic one quickly is useful.  

(all open to better visual aids, this was me working with what I could)

**Comment by drywallmud** [comment]
As power level is redundant in NPC sheets, I put a "B" to denote a basic attack:

![image](https://user-images.githubusercontent.com/5306827/136133902-f230638a-b619-44f6-aa18-0df20e7a1829.png)

**Comment by draconas1** [comment]
Oooh, that makes for a good solution and does not require any extra work for the sheet which I like even more :)
