### ISSUE TITLE
Damage Resistance is not following the rules

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#67]
I was testing the sheet, and I found some rules errors in damage resistances and weaknesses:

- An attack that deals two types of damage should only be resisted if the creature has resistance to both types of damage. A creature with resistance 5 acid should take full damage from an [acid, lightning] attack. Currently, it takes 5 fewer damage.
- A creature's resistances are being added together when it resists multiple damage types, so a target with resistance 5 acid and 5 lightning is taking 10 fewer damage from a [acid, lightning] attack.
- On the opposite, a creature that has vulnerability to more than one type of damage is currently adding the vulnerability toghether. For instance, a creature with weakness 5 acid and 5 lightning is taking 10 extra damage from an [acid, lightning] attack.
- Immunity to one type of damage is reducing the damage by half is the attack deals 2 types of damage. It shouldn't reduce the damage, and it should take no damage if it is immune to both damages.

Sorry if this is an already known issue.

**Comment by Marcloure** [comment]
Just a note, this is for the "apply damage" chat function.

**Comment by EndlesNights** [comment]
Oh geee, I've been house ruling this for so long to use a mix of math rules that I total slipped my mind that it was not RaW. I probably made the whole thing a tad bit more complicated then it needed to be as a result of this.

I'll sort this out and split it into two separate functions some time tomorrow. Thanks for the report

**Comment by Marcloure** [comment]
Fixed in pull #98
