### ISSUE TITLE
Issues with the Attack and Damage entries for powers.

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#7]
I have a few issues in this area.

First: When making a power such as "Bloodied Determination" where there is no attack or damage roll, the trigger and effect/flavor text input's do not post to chat because the attack and damage check boxes are turned off.

Second: If you uncheck the damage/effect box, but there is still information in the damage input fields, it will still post the damage button to chat. 

Third: There is no way to make the effect field post to my knowledge. No matter what I've tried, it will not output information. I use the "chat message flavor" field to do effects currently. However, this works for powers that have an attack roll and then have an effect, but it doesn't work for powers with no attack or damage roll.

Fourth: There is no way to target multiples of enemies that aren't a set number, such as "each enemy adjacent to the target".

Fifth: There is no way to make "follow-up" attacks without making another power entry. For example, any power that says "do this attack and if it hits, do this secondary attack."

Sixth: I can't find any way to make the requirements, special, or effect fields to output.

Those are the actual issues I know of currently, but here are some other suggested changes.

The description tab can currently be used to do powers that don't have attack and damage entries because the information in the description tab outputs on the original power card in chat above where the attack or damage buttons would be. However, you can only see the target(s) after clicking the attack button. I think it would be more user friendly to make the target(s), attack vs defense listing, requirements, special, trigger and flavor text fields all output to the first card instead of in the attack card after pressing the button. Currently, the description box and flavor text field would serve the same purpose, but I feel like this would work better. I would also, after making those changes, allow the user to disable the description tab from outputting, that way it can just be used for personal short-hand notes that the user can read on the character sheet to decide their turn, without that short-hand being output to chat.

**Comment by NuptupTDOW** [comment]
I was going to edit the above post to strike out what is fixed and what else I've found, but I think a fresh block will be easier to navigate. 

1: Most important to me personally, when you uncheck the damage box, the damage button will still post unless you manually delete every entry in the damage boxes of the power. Disabling the attack box works correctly now and does not need the owner to delete the attack line text.

2: Most of the special lines, such as effect, requirements, target, range, etc still only show up _after_ pressing either the damage or attack button, which still causes issues when you have an attack with an effect that deals no damage, as it will either not post, or it will only post after you press a useless damage button.

3: The description tab text posts correctly right under the name of the power when clicked, however the flavor text only appears when rolling the attack roll, the effect/hit/miss lines all only post when the damage button is pressed, and the effect types/keywords don't populate anywhere to my knowledge.
     3a: I would suggest either making all lines of a power post to the initial activation of the power so that you know all associated rolls, keywords, effects in one localized area, then have ONLY the attack itself tied to the attack button and ONLY the damage itself tied to the damage button. This helps fix a LOT of the issues I mentioned above where effect only shows up with the damage button, or flavor text only showing up with the attack button etc.
     3b: I have an alternative idea to resolve this problem, but it will likely result in a bigger overhaul, so I am instead going to make it it's own separate feature request and I will link it here. It involves the current work around method that I use for my powers by exclusively leaning on the description tab and using that format as a template for power blocks.

4: To my knowledge, there is no output for the "Trigger" box for powers. 

5: From my earlier post, "There is no way to target multiples of enemies that aren't a set number, such as "each enemy adjacent to the target"." I know there are more options, but I think a very easy option for you would be to add a new dropdown to the target section (like you did with area burst in powers range) which will just say "custom text" and it will allow the user to type anything in the second box. So, for example you could select "custom text" and then type in "All creatures controlled by the player named Bob." and it would post that instead of rejecting it because it's not a number. This would be an easy work around for all the various obscure targeting options so that you don't have to hunt down every single option and code it.

6: "There is no way to make "follow-up" attacks without making another power entry. For example, any power that says "do this attack and if it hits, do this secondary attack."" this is still true if I'm not mistaken. Currently the easiest work around is just making a separate power of course, but it'd be nice if it could have multiple attack entries in a single power. 


Hope this can prove helpful. If you have any questions whatsoever, please feel free to reach out to me here, or for a faster response, shoot me a discord message and I'll reply asap. I love the work you've put into this, and I don't want these long posts to come off as me nit-picking things. This system is absolutely amazing and you're doing incredible work on it. I just like to be able to help in any way I can, and currently it seems that's by troubleshooting it for you :D

**Comment by Marcloure** [comment]
I believe most of these issues have been fixed, or else they have other open issues to handle them, no? If that is the case, I think this issue should be closed.

**Comment by EndlesNights** [comment]
It's taken a while but for the most part all of theses issue have been sorted out, with a partial exception of making up follow up attacks. This can somewhat be done with the use of macro scripts which can be seen in example on "Steve, the Example character".
