### ISSUE TITLE
Typo in the Second Wind prompt

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#70]
"Additioanl Effects"

![image](https://user-images.githubusercontent.com/29084710/136469215-2c59752d-ce3b-46ee-aab5-4b4839a1124e.png)

**Comment by Marcloure** [comment]
> Regain an amount of **hitpoints equil** to 2.

Hit points should have a space.

![image](https://user-images.githubusercontent.com/29084710/136469483-15c75a99-65d1-4e52-8727-e2fca8411c0e.png)

**Comment by EndlesNights** [comment]
I'm sure their are a bunch of typos around that require my attention, thanks for pointing them out.

**Comment by drywallmud** [comment]
Another here:
![image](https://user-images.githubusercontent.com/5306827/137835456-83af7ee5-e429-4cd9-9606-2da5f6b8893c.png)

**Comment by drywallmud** [comment]
> "Additioanl Effects"
> 
> ![image](https://user-images.githubusercontent.com/29084710/136469215-2c59752d-ce3b-46ee-aab5-4b4839a1124e.png)

"Savingthrow Bonues" -> "Saving Throw Bonuses" (in the window title bar)
