### ISSUE TITLE
Add Limited Uses per Round

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#78]
![image](https://user-images.githubusercontent.com/29084710/139372682-de208480-6d89-422b-89d2-3993949b0747.png)

The "Limited Uses" field has only uses per encounter, day, or charges, but it should have a use per turn as well. The pit fiend, for instance, has a minor action that can be used only 1/round:

![image](https://user-images.githubusercontent.com/29084710/139372805-ddbea98f-a73b-4080-9375-151c29e2cee0.png)

**Comment by Gallatus** [comment]
I find the same for hunter's quarry, warlock's curse and sneak attack.

**Comment by NuptupTDOW** [comment]
Agreed, this would be nice for stuff like assassin's shroud and warden mark as well.
