### ISSUE TITLE
Issue with attack formula when adding attributes

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#8]
While imputing some formulas into the weapon entry, I am having a very odd glitch occur. I am trying to make it so that the character level on the sheet is added to attack and damage rolls by incorporating the "@details.level" attribute into the attack and damage formula. The weapon entries read as follows:

Weapon damage dice number: 1
Weapon damage dice size: 6
Bonus to Attack formula: 5+@details.level
Bonus to Primary Damage formula: 4+@details.level

Power Formulas
Attack Formula: 1d20+@wepAttack
Damage Formula: (1*@wepDiceNum) d@wepDiceDamage + @powerMod + @wepDamage
Critical Damage Formula: 1*@wepDiceNum*@wepDiceDamage+@powerMod+@wepCritBonus

So anyway, the issue I'm having is that, when clicking a power using that "weapon" it will post the block to the chat panel, and when I click damage, it rolls no issues and reads "1d6+4+1" which is correct and it totals up to "1d6+5" however when I click the attack button, it says that there is no attribute for "details.level" in a yellow banner at the top of screen, but it still rolls it. The issue is that, according to what the box says, it is rolling "1d20+5+0" and not adding the character level, but when you check the dice math, it is the correct math. So, of you roll a 4, it would output a total of 10, not 9, even though it claims to not include the character level. 

When I get to my pc, I will take a screenshot and add it.

**Comment by NuptupTDOW** [comment]
For some reason I can't send the screen shot right now.., I'll send it on discord on my next break at work.

**Comment by NuptupTDOW** [comment]
New issue arose with the new update. 

In a power, if I put "1d20+5" it works fine and rolls 1d20 + 5, and if I use the @lv that you mentioned on discord it works, which is great, but if I put "1d20+5+@details.level" it rolls "1d205 + 0". Not the end of the world since i'm going to just change them all to the @lv, just wanted to let you know in case it could cause some side effects down the road.

**Comment by EndlesNights** [comment]
Ahhh I see that I made a small mistake with the RegExr where it doesn't properly check the last term, but if you where to do 1d20+@details.level+5 it would work. Wooops Well I've fixed this for the next patch.
