### ISSUE TITLE
Increased Functionality for the Role and Rank drop-downs on the NPC sheet.

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#84]
Would it be possible to have a checkbox added to the sheet (or make this request added on to the "Advanced Math Options:" button) so that when you turn it on it will auto-populate the defenses and whatnot for the creature according to the MM3 business card math? 

For example, If I want to make a brand new level 5 Solo Brute NPC, I could turn on advanced math, then set their level to 5, select brute and solo from the drop downs, and the sheet would automatically populate the sheet with 19 AC, 17 NADs, 10 To-Hit, and 55 HP as a basic level 5, then it would apply brute by making 17 AC and 18 Fort and finally bump HP to 220 from solo. All with 4 inputs via turning on math, setting level, setting brute, setting solo. 

I currently replicate this with "Equipment" slots that are just the raw math and I equip them based on what the creature is, but that leaves the drop downs functionally pointless. So, I figured we could use them for this. Also, one request, since some of us use revised math, or we like separating dumb brutes (-1 will instead) from clumsy brutes (-1 ref), would it be possible to make the role and rank drop downs default to the MM3 business card values, but have an option in the system settings menu that can open up a table where you can add or remove roles and ranks, and adjust their intrinsic values to accommodate this?

This whole idea is just to allow dm's to make npc's very fast (probably faster than directly copying all the information into a blank sheet) while also (if the settings table idea is implemented) fully supporting a vast number of math fix solutions different tables use to speed up their games (such as less HP, but bigger damage to make it more fast pace and high stakes) and make the system more moldable to their desired specs with an easy to adjust table of data.

Even if the adjustable math doesn't end up being a thing (I hope it will), I think the drop-down selections should at least match the MM3 card when the Advanced Math Options (or a different checkbox) is enabled.

**Comment by draconas1** [comment]
I definitely don't want this added to advanced math as it will break all monsters I import from masterplan who rely on the existing functionality.

**Comment by NuptupTDOW** [comment]
Hmmm, so I hadn't really considered that. Maybe as an alternative then? Just like, normal, then "advanced math" then "MM3 Automath"?

**Comment by draconas1** [comment]
So for this I have created a macro in my tools that will let you set these quickly:

You need the latest version of https://github.com/draconas1/foundry-4e-tools  (1.2.1, released 5 minutes ago)

This includes a "Drac's Items" compendium, which currently has a single thing: a class feature that wraps a macro that sets these values.  Set the level and role in the monster drop downs, drag your class feature onto the character and run it (click the dice to output it to the chat), the macro will run and set a bunch of values as appropreate for MM3 on the a business card.  The macro itself should be fairly self explanatory to tweak with different values.

**Comment by NuptupTDOW** [comment]
Huh, That's pretty cool actually. I was doing it with just equipment pieces that I would drag and drop on to the character that signed them the correct stats, but that works too! Thanks a bunch!
