### ISSUE TITLE
Rapier in compendium should be a Military weapon, not Superior.

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#86]
The rapier was originally a superior weapon in the Player's Handbook. The Essentials rulebooks changed it to a military weapon.

I imagine you might be setting it only to what was stated in the PHB1, but this could be rather troublesome down the road as a compendium item to not include a later errata. I don't know for sure what the legal rule here is for what you can set in your sheet, but just wanted to mention it.

**Comment by draconas1** [comment]
Given the huge diffs in essentials, and that essentials books are not even mentioned in the SRD, I think it has to stay RAW in PHB so remains a superior weapon.

We can stick a note in the description about diffs in essentials, in the same way that I used description to note minimum enchantment bonus for mastercrafted armour.

**Comment by Garthanos** [comment]
Anyone using CBloader and the updates that have been compiled will also be expecting the military version of it.

**Comment by draconas1** [comment]
I have double checked this one, including a trawl through the godawful mess that is the 4E Errata document (140 pages, no index or table of contents).  

And while Essentials / MME are most definitely not SRD material, and thus we can't use them, buried on page 109 of the Errata doc is an update to the Rapier.  Since it's an update to the published source, which is an SRD material, that seems pretty golden to me and I will update our version and leave a note.

**Comment by draconas1** [comment]
Hilarious The update is, and I quote:
_Page 218: The weapon is longer a superior military weapon._

Doesn't actually say what it should be.... Simple Ranged Rapiers anyone?  :P

**Comment by sharkbruhaha** [comment]
Why would you expect a tabkf of contents or index, pfft :p /s

**Comment by draconas1** [comment]
I know, next time I will even be wanting them to specify what something is rather than just what it is not.

**Comment by sharkbruhaha** [comment]
Could we just have it in both ways, with the ES version having it in the
name too?

**Comment by sharkbruhaha** [comment]
Whoah now! Entitled much?!

**Comment by draconas1** [comment]
Have tested this as updated in 0.2.51.  I can't close this as I didn't raise it.
