### ISSUE TITLE
Can't roll anything

### ISSUE THREAD

**Issue by Gallatus** [EndlesNights/dnd4eBeta#87]
First of all, kudos to the 4th edition initiative!
This might be a very noobish question, but i can't roll anything using shortcuts from character sheet: 

![image](https://user-images.githubusercontent.com/93723921/140339577-c47c0f2d-f911-45e0-b78c-ee3f87de6172.png)

I'm doing something wrong?

**Comment by EndlesNights** [comment]
Sorry for being slow to get back to you. Ability checks should be strait forward just clicking roll. If you uninstall and reinstall the system does the issue still persists? And if it does, could you open up the console and copy the error message to me please?

**Comment by Gallatus** [comment]
It's all good now. I think it might had to do with the foundry vtt version i was testing (9.220).  Since then, i've change my game to this system. Can't wait to give it a go with my party.

**Comment by draconas1** [comment]
Ah yes, that would have caused it - looking at the date you posted this was before the work we did to make it V9 compatible, so many of the macros would have crashed with errors in v9.
