### ISSUE TITLE
Add option for inherent enhancement bonus

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#88]
The DMG 2 presents an option for auto-scaling enhancement bonus for attacks, damage and defense. See: https://dnd4.fandom.com/wiki/Fixed_enhancement_bonus

This can be done using custom effects and manually scaling the item bonuses, but it would be nice to have a sheet option that handles all of that, if possible. It's a low priority feature, of course.

**Comment by Garthanos** [comment]
this I would like too.

**Comment by FoxLee** [comment]
I would greatly appreciate this too!

**Comment by NuptupTDOW** [comment]
4th'd

**Comment by EndlesNights** [comment]
Thank the Fox!
