### ISSUE TITLE
Hit field should display even when there is no attack

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#90]
Some powers have the "Hit" field without making an attack roll. For instance:

![image](https://user-images.githubusercontent.com/29084710/140527874-7e8ea1ca-0fd0-4c3b-b70e-238b5cc5ccc7.png)

Currently, if you uncheck the "Attack Roll Required?" toggle, it also doesn't display the "Hit" field. I think these should not be dependant on each other.

**Comment by EndlesNights** [comment]
From now on the Hit field will only be dependent on if the hit.detail value is truthy.
