### ISSUE TITLE
Create a "Before Effect" field

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#91]
Some powers have effects that happen _before_ the attack roll. It would be nice to have an optional Effect and a Special field that is written before the attack roll. For instance:

![image](https://user-images.githubusercontent.com/29084710/140529176-47b72213-7595-4fa7-ab0f-ac4f56cd19c7.png)

**Comment by EndlesNights** [comment]
This is already an option, where if you uncheck the box "_Display Information Post Attack Details?_" above and to the right of the the effect details, it will be printed above the attack roll text.

Though currently the highlighting does not work as intended, so I will fix that right now for the dev stream
