### ISSUE TITLE
[Feature Request] Add a way to reorder items

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#93]
Gear and Feats can get a rather cluttered since you can't reorder them. I think they should have some kind of drag to reorder functionality. Maybe powers would be an exception, since they already have a sorting method.

**Comment by NuptupTDOW** [comment]
I would highly second this. As well as also including powers.

**Comment by Marcloure** [comment]
Powers have a sorting feature. I'm thinking of adapting that to feats, but by name, since feats don't have a level

**Comment by Marcloure** [comment]
Feats can now be sorted as part of https://github.com/EndlesNights/dnd4eBeta/pull/104.
