### ISSUE TITLE
Add global attack and damage modifier to accomodate feats

### ISSUE THREAD

**Issue by Marcloure** [EndlesNights/dnd4eBeta#94]
Feats like **weapon expertise** and **weapon focus** add a bonus to attack or damage rolls of all weapons of a certain type. However, there is no way to add this bonus to the weapons or a Passive Effect that affects the items.

A solution I thought was to add a generic attribute to actors like "attack.feat" and "damage.feat", which can be manually added to the damage and attack formula of implements and weapons.

**Comment by EndlesNights** [comment]
Added into the dev stream in pull #98
